# Faroese (Føroyskt) person names — Faroe Islands (fo_FO)

from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{prefix_male}} {{first_name_male}} {{last_name}}",
    )

    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{prefix_female}} {{first_name_female}} {{last_name}}",
    )

    formats = formats_male + formats_female

    # Faroese male first names
    first_names_male = (
        "Jógvan",
        "Petur",
        "Hanus",
        "Heri",
        "Tróndur",
        "Sjúrður",
        "Bárður",
        "Rógvi",
        "Óli",
        "Jákup",
        "Símun",
        "Poul",
        "Kári",
        "Eyðun",
        "Regin",
        "Magnus",
        "Torkil",
        "Leivur",
        "Fróði",
        "Súni",
        "Bogi",
        "Dánjal",
        "Andrass",
        "Absalon",
        "Tummas",
        "Elias",
        "Kristian",
        "Niklái",
        "Marius",
        "Hjalti",
        "Høgni",
        "Bjørn",
        "Gunnar",
        "Egil",
        "Finnur",
        "Ásmundur",
        "Villjormur",
        "Zacharias",
        "Jóhannes",
        "Mikkjal",
        "Hentzar",
        "Palli",
        "Rasmus",
        "Hákun",
        "Jóannes",
        "Hedin",
        "Fríðrikur",
        "Leif",
        "Ari",
        "Árni",
        "Áki",
        "Alvur",
        "Andrias",
        "Beinir",
        "Benjamin",
        "Bergur",
        "Birgir",
        "Brandur",
        "Dávur",
        "Edvard",
        "Eiríkur",
        "Eli",
        "Emil",
        "Erlendur",
        "Esbern",
        "Eysteinur",
        "Frants",
        "Gestur",
        "Gilli",
        "Grækaris",
        "Guttormur",
        "Hallur",
        "Hannis",
        "Haraldur",
        "Herálvur",
        "Herluf",
        "Hilmar",
        "Hjørleivur",
        "Ingálvur",
        "Ívar",
        "Jaspur",
        "Jóhan",
        "Jón",
        "Justi",
        "Ketil",
        "Klæmint",
        "Knútur",
        "Kristoffur",
        "Leon",
        "Ludvig",
        "Marni",
        "Martin",
        "Mikael",
        "Mourits",
        "Niels",
        "Oddvar",
        "Ólavur",
        "Osvald",
        "Páll",
        "Peter",
        "Ríkard",
        "Rúni",
        "Sámal",
        "Sigmundur",
        "Sigurd",
        "Snorri",
        "Steffan",
        "Sven",
        "Teitur",
        "Tórður",
        "Torleivur",
        "Torsteinur",
        "Tóki",
        "Uni",
        "Valdemar",
        "Valentin",
        "Vilhelm",
        "Meinhard",
        "Guðmundur",
        "Ísakur",
        "Alexander",
        "Bertel",
        "Frímann",
        "Trygvi",
    )

    # Faroese female first names
    first_names_female = (
        "Rannvá",
        "Elin",
        "Beinta",
        "Óluva",
        "Barbara",
        "Marjun",
        "Turið",
        "Sanna",
        "Ester",
        "Anna",
        "Katrina",
        "Malena",
        "Elisabeth",
        "Sunnvá",
        "Guðrun",
        "Durita",
        "Bjørg",
        "Ingun",
        "Sigrun",
        "Sólrun",
        "Hervør",
        "Bergtóra",
        "Signhild",
        "Rakul",
        "Súsanna",
        "Petra",
        "Kristina",
        "Marja",
        "Hjørdis",
        "Vár",
        "Fríða",
        "Herborg",
        "Jóhanna",
        "Dagny",
        "Randi",
        "Karin",
        "Marin",
        "Sólvá",
        "Tóra",
        "Birita",
        "Bára",
        "Annika",
        "Súsan",
        "Eyðvør",
        "Halla",
        "Rebekka",
        "Kristin",
        "Maria",
        "Alma",
        "Andrea",
        "Ann",
        "Annlís",
        "Annleyg",
        "Ása",
        "Astrid",
        "Bergljót",
        "Betty",
        "Birna",
        "Bóel",
        "Borgny",
        "Brá",
        "Brynhild",
        "Debora",
        "Ditta",
        "Dorit",
        "Edith",
        "Eydna",
        "Eyðbjørt",
        "Fía",
        "Gerð",
        "Guðny",
        "Gunn",
        "Gunnvør",
        "Hallbera",
        "Hallgerð",
        "Heiða",
        "Helena",
        "Henrietta",
        "Ingebjørg",
        "Ingrid",
        "Jana",
        "Jenny",
        "Jórun",
        "Júlia",
        "Karla",
        "Katla",
        "Kirstin",
        "Laila",
        "Lena",
        "Lilja",
        "Liljan",
        "Linda",
        "Lisbeth",
        "Liv",
        "Magga",
        "Malan",
        "Marna",
        "Margit",
        "Matilda",
        "Mette",
        "Oddný",
        "Olga",
        "Rigmor",
        "Rósa",
        "Ronja",
        "Rúna",
        "Salvør",
        "Sára",
        "Selma",
        "Sigga",
        "Silja",
        "Suffía",
        "Sólveig",
        "Sonja",
        "Torbjørg",
        "Tordís",
        "Torvør",
        "Ulrikka",
        "Unn",
        "Vigdis",
        "Vilborg",
        "Ýrsa",
        "Halldóra",
        "Kristjanna",
    )

    first_names = first_names_male + first_names_female

    # Faroese surnames (mostly patronymic -sen forms plus native Faroese names)
    last_names = (
        "Joensen",
        "Hansen",
        "Jacobsen",
        "Petersen",
        "Poulsen",
        "Olsen",
        "Thomsen",
        "Danielsen",
        "Rasmussen",
        "Nielsen",
        "Johansen",
        "Simonsen",
        "Mortensen",
        "Andreasen",
        "Jensen",
        "Djurhuus",
        "Højgaard",
        "Debes",
        "Dam",
        "á Rógvi",
        "í Stovu",
        "Mikkelsen",
        "Michelsen",
        "Larsen",
        "Frederiksen",
        "Christiansen",
        "Samuelsen",
        "Isaksen",
        "Bærentsen",
        "Winther",
        "Reinert",
        "Egholm",
        "Fossá",
        "Ellingsgaard",
        "Holm",
        "Berg",
        "Vang",
        "Justinussen",
        "Nolsøe",
        "Zachariassen",
        "Skaale",
        "Sørensen",
        "Weihe",
        "Restorff",
        "Effersøe",
        "Patursson",
        "Biskopstø",
        "Klein",
    )

    prefixes_male = (
        "Harra",
        "Dr.",
    )

    prefixes_female = (
        "Frúa",
        "Frøkun",
        "Dr.",
    )

    prefixes = prefixes_male + prefixes_female
