from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{prefix_male}} {{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}-{{last_name}}",
    )

    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{prefix_female}} {{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}-{{last_name}}",
    )

    formats = formats_male + formats_female

    first_names_male = (
        "Arben",
        "Agron",
        "Altin",
        "Ardian",
        "Ardit",
        "Astrit",
        "Bardhyl",
        "Bekim",
        "Besart",
        "Besnik",
        "Blerim",
        "Bujar",
        "Dorian",
        "Drilon",
        "Driton",
        "Dritan",
        "Edon",
        "Endrit",
        "Ermal",
        "Erjon",
        "Fatmir",
        "Fatos",
        "Florian",
        "Genti",
        "Gentian",
        "Gëzim",
        "Granit",
        "Hekuran",
        "Ilir",
        "Jetmir",
        "Kastriot",
        "Klodian",
        "Kreshnik",
        "Leotrim",
        "Luan",
        "Lulzim",
        "Mentor",
        "Mërgim",
        "Naim",
        "Naser",
        "Petrit",
        "Ramadan",
        "Rexhep",
        "Shpëtim",
        "Skënder",
        "Sokol",
        "Taulant",
        "Valon",
        "Xhevat",
        "Ylli",
        "Zamir",
    )

    first_names_female = (
        "Adelina",
        "Albana",
        "Anila",
        "Ardita",
        "Arta",
        "Besa",
        "Blerta",
        "Brikena",
        "Dafina",
        "Donika",
        "Dorina",
        "Drita",
        "Edona",
        "Elira",
        "Ermira",
        "Erisa",
        "Fatime",
        "Flutura",
        "Genta",
        "Gentiana",
        "Hana",
        "Ilirjana",
        "Jehona",
        "Jonida",
        "Kaltrina",
        "Klodiana",
        "Lindita",
        "Luljeta",
        "Majlinda",
        "Manjola",
        "Merita",
        "Mimoza",
        "Nertila",
        "Nora",
        "Olta",
        "Pranvera",
        "Qëndresa",
        "Rina",
        "Rita",
        "Sadete",
        "Shpresa",
        "Suela",
        "Teuta",
        "Valbona",
        "Vera",
        "Vjosa",
        "Vlora",
        "Xhensila",
        "Ylberë",
        "Zana",
    )

    first_names = first_names_male + first_names_female

    last_names = (
        "Ahmeti",
        "Bajrami",
        "Bardhi",
        "Basha",
        "Beqiri",
        "Berisha",
        "Bregu",
        "Cani",
        "Çela",
        "Dedaj",
        "Dervishi",
        "Doçi",
        "Duka",
        "Elezi",
        "Frashëri",
        "Gashi",
        "Gjoni",
        "Halili",
        "Hasani",
        "Hoxha",
        "Ismaili",
        "Kadare",
        "Kelmendi",
        "Kola",
        "Krasniqi",
        "Kuqi",
        "Lala",
        "Leka",
        "Lleshi",
        "Marku",
        "Meta",
        "Murati",
        "Mustafa",
        "Ndreu",
        "Nika",
        "Osmani",
        "Prifti",
        "Rama",
        "Ramadani",
        "Rexhepi",
        "Selmani",
        "Shala",
        "Sula",
        "Tahiri",
        "Toska",
        "Vata",
        "Veliu",
        "Xhaka",
        "Zeneli",
        "Zogu",
    )

    prefixes_male = ("Z.", "Dr.", "Prof.")
    prefixes_female = ("Znj.", "Znjsh.", "Dr.", "Prof.")
    prefixes = ("Z.", "Znj.", "Znjsh.", "Dr.", "Prof.")
