from .. import Provider as PersonProvider


class Provider(PersonProvider):

    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}-{{last_name}}",
        "{{prefix}} {{first_name_male}} {{last_name}}",
    )

    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}-{{last_name}}",
        "{{prefix}} {{first_name_female}} {{last_name}}",
    )

    formats = formats_male + formats_female

    # Authentic Luxembourgish male first names (Latin script)
    first_names_male = (
        "Jann",
        "Jean",
        "Marc",
        "Michel",
        "Paul",
        "Pierre",
        "Nico",
        "Camille",
        "Fernand",
        "Guy",
        "Henri",
        "Gilbert",
        "Roland",
        "Aloyse",
        "Théid",
        "Jempy",
        "Metty",
        "Batty",
        "Nickel",
        "Jos",
        "Josy",
        "Mathias",
        "Norbert",
        "Robert",
        "Romain",
        "René",
        "Raymond",
        "Serge",
        "Georges",
        "François",
        "Claude",
        "Emile",
        "Ernest",
        "Victor",
        "Léon",
        "Charel",
        "Dan",
        "Ben",
        "Luc",
        "Max",
        "Tom",
        "Yves",
        "Pit",
        "Fränz",
        "Nesa",
        "Alphonse",
    )

    # Authentic Luxembourgish female first names (Latin script)
    first_names_female = (
        "Chantal",
        "Anne",
        "Josée",
        "Marie",
        "Jeanne",
        "Françoise",
        "Simone",
        "Monique",
        "Nathalie",
        "Martine",
        "Danielle",
        "Nicole",
        "Sylvie",
        "Carole",
        "Michèle",
        "Corinne",
        "Fabienne",
        "Isabelle",
        "Liette",
        "Malou",
        "Marguerite",
        "Marianne",
        "Suzette",
        "Yolande",
        "Astrid",
        "Colette",
        "Denise",
        "Gaby",
        "Gaston",
        "Henriette",
        "Joëlle",
        "Léa",
        "Marceline",
        "Milly",
        "Netty",
        "Roseline",
        "Tessy",
        "Viviane",
        "Charlotte",
        "Emma",
        "Léonie",
        "Marta",
        "Nora",
        "Sophie",
        "Julie",
        "Lynn",
    )

    first_names = first_names_male + first_names_female

    # Source for last names: https://nachnamen.net/luxemburg
    last_names = (
        "Schmit",
        "Muller",
        "Weber",
        "Wagner",
        "Hoffmann",
        "Thill",
        "Schmitz",
        "Schroeder",
        "Becker",
        "Klein",
        "Faber",
        "Kieffer",
        "Reuter",
        "Schiltz",
        "Welter",
        "Simon",
        "Schneider",
        "Hansen",
        "Meyer",
        "Kremer",
        "Weis",
        "Braun",
        "Kayser",
        "Kirsch",
        "Steffen",
        "Krier",
        "Theisen",
        "Majerus",
        "Ries",
        "Meyers",
        "Engel",
        "Schumacher",
        "Diederich",
        "Martin",
        "Marx",
        "Molitor",
        "Theis",
        "Wolff",
        "Heinen",
        "Weydert",
        "Zimmer",
        "Feltz",
        "Wies",
        "Origer",
        "Reiff",
        "Frantz",
        "Berg",
        "Hein",
        "Gengler",
        "Peters",
    )

    prefixes = (
        "Här",
        "Madame",
        "Dokter",
        "Professer",
    )
