from .. import Provider as PersonProvider


class Provider(PersonProvider):
    """
    A Faker provider for generating fake Shona names in Zimbabwe.
    """

    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{first_name_male}} {{last_name}}",
        "{{prefix_male}} {{first_name_male}} {{last_name}}",
    )

    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{first_name_female}} {{last_name}}",
        "{{prefix_female}} {{first_name_female}} {{last_name}}",
    )

    formats = formats_male + formats_female

    # Authentic Shona (chiShona) given names, written in the Latin script.
    first_names_male = (
        "Tendai",
        "Farai",
        "Tafadzwa",
        "Tinashe",
        "Simba",
        "Simbarashe",
        "Kudakwashe",
        "Takudzwa",
        "Munashe",
        "Tanaka",
        "Panashe",
        "Anesu",
        "Tapiwa",
        "Batsirai",
        "Garikai",
        "Tonderai",
        "Munyaradzi",
        "Tatenda",
        "Ngonidzashe",
        "Rangarirai",
        "Kundai",
        "Farirai",
        "Shingirai",
        "Tichaona",
        "Nhamo",
        "Takunda",
        "Tavonga",
        "Tadiwanashe",
        "Kudzai",
        "Chenjerai",
        "Tarisai",
        "Ngoni",
        "Rugare",
        "Tichafa",
        "Fungai",
        "Gamuchirai",
        "Tavengwa",
        "Tanyaradzwa",
        "Munyaradzwa",
        "Rutendo",
        "Blessing",
        "Tawanda",
        "Tapfumaneyi",
        "Vengai",
        "Chatunga",
        "Mufaro",
    )

    first_names_female = (
        "Rutendo",
        "Chipo",
        "Rufaro",
        "Nyasha",
        "Vimbai",
        "Ropafadzo",
        "Tariro",
        "Rumbidzai",
        "Fadzai",
        "Chiedza",
        "Anesu",
        "Tsitsi",
        "Nyaradzai",
        "Shamiso",
        "Tanyaradzwa",
        "Chido",
        "Ruvimbo",
        "Nyarai",
        "Chenai",
        "Nokutenda",
        "Rudo",
        "Ratidzo",
        "Vongai",
        "Farirai",
        "Muchaneta",
        "Tapiwanashe",
        "Mazvita",
        "Kupakwashe",
        "Simbisai",
        "Chiratidzo",
        "Yeukai",
        "Rufaro",
        "Netsai",
        "Chiedza",
        "Rejoice",
        "Precious",
        "Memory",
        "Sekai",
        "Rombai",
        "Rungano",
        "Nyengeterai",
        "Chidochashe",
        "Tanaka",
        "Kundai",
        "Rutendo",
        "Chengetai",
    )

    first_names = first_names_male + first_names_female

    # Authentic Zimbabwean (predominantly Shona) family names.
    last_names = (
        "Moyo",
        "Mutasa",
        "Makoni",
        "Marufu",
        "Mangwiro",
        "Chidzambwa",
        "Mujuru",
        "Zvobgo",
        "Chinamasa",
        "Chiwenga",
        "Mnangagwa",
        "Mahachi",
        "Mutambara",
        "Chikwava",
        "Gumbo",
        "Mudenda",
        "Chikwanha",
        "Zhou",
        "Gwerevende",
        "Mombeyarara",
        "Chatora",
        "Chuma",
        "Madziwa",
        "Mahere",
        "Mataka",
        "Chirinda",
        "Gwatidzo",
        "Mudzuri",
        "Chihota",
        "Mukono",
        "Nhongo",
        "Mahoso",
        "Rusike",
        "Chikukwa",
        "Marange",
        "Chikafu",
        "Musarurwa",
        "Machingura",
        "Gomba",
        "Chipunza",
        "Mabika",
        "Chinyama",
        "Mudede",
        "Chikonzo",
        "Muchemwa",
        "Chimhini",
        "Mangwende",
        "Kanengoni",
        "Mudariki",
        "Chivaura",
        "Rwodzi",
        "Chigwedere",
        "Mupfumira",
        "Zvomuya",
    )

    # Common Shona and Zimbabwean honorifics.
    prefixes = (
        "Mr.",
        "Mrs.",
        "Miss",
        "Dr.",
        "Prof.",
        "Baba",
        "Amai",
        "Sekuru",
        "Mbuya",
        "Tete",
        "VaMukoma",
    )
