from collections import OrderedDict

from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{prefix}} {{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}-{{last_name}}",
    )

    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{prefix}} {{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}-{{last_name}}",
    )

    formats = formats_male + formats_female

    # Authentic Hawaiian (ʻōlelo Hawaiʻi) given names, written in the Latin
    # script with the ʻokina and kahakō (macron) as used in Hawaiʻi.
    first_names_male = (
        "Kai",
        "Keanu",
        "Kekoa",
        "Koa",
        "Nainoa",
        "Ikaika",
        "Makoa",
        "Keoni",
        "Kimo",
        "Keola",
        "Kalani",
        "Kawika",
        "Palani",
        "Kanoa",
        "Keahi",
        "Kōnane",
        "Lono",
        "Kāne",
        "Noa",
        "Pekelo",
        "Akamu",
        "Ekewaka",
        "Haoa",
        "Hōkū",
        "Kaipo",
        "Kaleo",
        "Aukai",
        "Kaimana",
        "Kaʻeo",
        "Mano",
        "Nalu",
        "Nohea",
        "Manu",
        "Alakaʻi",
        "Lōkahi",
        "Maka",
        "Kekipi",
        "Anakoni",
        "Iona",
        "Kamana",
        "Kolomona",
        "Kimokeo",
        "Kaʻimi",
        "Kekemekia",
        "Kāwelu",
    )

    first_names_female = (
        "Leilani",
        "Malia",
        "Kealoha",
        "Nohealani",
        "Ululani",
        "Mahina",
        "Iolana",
        "Noelani",
        "Pua",
        "Puanani",
        "Lani",
        "Aloha",
        "Anela",
        "Healani",
        "Kalena",
        "Kanani",
        "Kaulana",
        "Keala",
        "Keilani",
        "Kiele",
        "Lilinoe",
        "Makana",
        "Momi",
        "Nani",
        "Noe",
        "Oliana",
        "Pilialoha",
        "Roselani",
        "Uʻilani",
        "Wehilani",
        "Kaʻiulani",
        "Kapua",
        "Lokelani",
        "Miliani",
        "Napua",
        "ʻOkalani",
        "Alohilani",
        "Haukea",
        "Kāwena",
        "Lehua",
        "Melia",
        "Nālani",
        "ʻIlima",
        "Kehaulani",
        "Hiʻilani",
    )

    first_names = first_names_male + first_names_female

    # Authentic Hawaiian ʻohana (family) names / surnames.
    last_names = OrderedDict(
        (
            ("Kealoha", 1.0),
            ("Kamaka", 1.0),
            ("Kanahele", 1.0),
            ("Kahale", 1.0),
            ("Akana", 1.0),
            ("Akau", 1.0),
            ("Akiona", 1.0),
            ("Alapaʻi", 1.0),
            ("Auwae", 1.0),
            ("Hema", 1.0),
            ("Iaukea", 1.0),
            ("Kaʻai", 1.0),
            ("Kahanu", 1.0),
            ("Kalāhiki", 1.0),
            ("Kanakaʻole", 1.0),
            ("Kupihea", 1.0),
            ("Naeole", 1.0),
            ("Poepoe", 1.0),
            ("Kekahuna", 1.0),
            ("Kahoʻohalahala", 1.0),
            ("Nāhaʻolelua", 1.0),
            ("Kaleikini", 1.0),
            ("Keliʻikoa", 1.0),
            ("Kaʻaihue", 1.0),
            ("Kaʻanāʻanā", 1.0),
            ("Kealiʻi", 1.0),
            ("Keawe", 1.0),
            ("Kekona", 1.0),
            ("Kaʻawa", 1.0),
            ("Nāone", 1.0),
            ("Hoʻopiʻi", 1.0),
            ("Kaʻapuni", 1.0),
            ("Kekuewa", 1.0),
            ("Makuakāne", 1.0),
            ("Kealohapauʻole", 1.0),
            ("Kanoho", 1.0),
            ("Nāleimaile", 1.0),
            ("Kaneakua", 1.0),
            ("Pōʻai", 1.0),
            ("Kekūmano", 1.0),
            ("Kaʻiliʻohu", 1.0),
            ("Naipo", 1.0),
            ("Kealohanui", 1.0),
            ("Kahaunani", 1.0),
        )
    )

    # Hawaiian honorifics / terms of respect used before a name.
    prefixes = ("Kumu", "Kupuna", "Aliʻi", "Tūtū", "Makua")
