from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}-{{last_name}}",
        "{{prefix_male}} {{first_name_male}} {{last_name}}",
    )

    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}-{{last_name}}",
        "{{prefix_female}} {{first_name_female}} {{last_name}}",
    )

    formats = formats_male + formats_female

    # Authentic Maltese masculine given names (Latin script, incl. Maltese
    # letters Ċ ċ, Ġ ġ, Ħ ħ, Ż ż).
    first_names_male = (
        "Ġużeppi",
        "Ġorġ",
        "Ġwann",
        "Ġanni",
        "Karmnu",
        "Karm",
        "Kalċidon",
        "Salvu",
        "Salvatur",
        "Wenzu",
        "Żaren",
        "Żeppi",
        "Toni",
        "Anġlu",
        "Anton",
        "Pawlu",
        "Pietru",
        "Nazzareno",
        "Nikol",
        "Mikiel",
        "Mattew",
        "Publju",
        "Emanwel",
        "Manwel",
        "Grezzju",
        "Guido",
        "Kelinu",
        "Ċensu",
        "Ċikku",
        "Ċetta",
        "Baskal",
        "Bastjan",
        "Indri",
        "Indrì",
        "Filippu",
        "Frans",
        "Ġakbu",
        "Ġużè",
        "Lorenz",
        "Lawrenz",
        "Mario",
        "Nardu",
        "Notar",
        "Rikardu",
        "Rokku",
        "Spiru",
        "Vitor",
        "Xandru",
        "Żakkarija",
        "Ġiljan",
        "Dun",
        "Ċikkuż",
    )

    # Authentic Maltese feminine given names.
    first_names_female = (
        "Marija",
        "Mari",
        "Marì",
        "Rożi",
        "Rożann",
        "Karmena",
        "Karmni",
        "Ġużeppa",
        "Ġanna",
        "Ġovanna",
        "Grazzja",
        "Grezzja",
        "Duminka",
        "Ċetta",
        "Ċettina",
        "Nina",
        "Ninu",
        "Pawla",
        "Pola",
        "Filomena",
        "Fela",
        "Ġorġina",
        "Katarina",
        "Ketty",
        "Lolli",
        "Loreta",
        "Lucija",
        "Luċija",
        "Manwela",
        "Marċella",
        "Nazzarena",
        "Onda",
        "Pina",
        "Rita",
        "Rożarja",
        "Saveria",
        "Speranza",
        "Sperenza",
        "Stella",
        "Terezina",
        "Vitorja",
        "Żabbett",
        "Żabbetta",
        "Elena",
        "Doris",
        "Antonia",
        "Anġela",
        "Anġelina",
        "Betta",
        "Bettina",
    )

    # Common Maltese surnames.
    last_names = (
        "Borg",
        "Camilleri",
        "Vella",
        "Farrugia",
        "Zammit",
        "Galea",
        "Micallef",
        "Grech",
        "Attard",
        "Spiteri",
        "Azzopardi",
        "Bonnici",
        "Caruana",
        "Cassar",
        "Fenech",
        "Muscat",
        "Grima",
        "Abela",
        "Agius",
        "Debono",
        "Mifsud",
        "Sultana",
        "Aquilina",
        "Cutajar",
        "Falzon",
        "Xuereb",
        "Scicluna",
        "Schembri",
        "Sciberras",
        "Gauci",
        "Buttigieg",
        "Calleja",
        "Pace",
        "Portelli",
        "Bugeja",
        "Saliba",
        "Cachia",
        "Chircop",
        "Ellul",
        "Gatt",
        "Magro",
        "Mallia",
        "Mizzi",
        "Tabone",
        "Vassallo",
        "Zahra",
        "Zarb",
        "Grixti",
        "Psaila",
        "Xerri",
        "Cachia",
        "Baldacchino",
    )

    prefixes_female = ("Sinjura", "Sinjorina", "Dr", "Perit", "Onor.")
    prefixes_male = ("Sinjur", "Dr", "Perit", "Kav.", "Onor.")

    prefixes = ("Sinjur", "Sinjura", "Sinjorina", "Dr", "Perit")
