from .. import Provider as PersonProvider


class Provider(PersonProvider):
    """
    Occitan (Latin script) names.

    Native Occitan given names and surnames as attested in Occitania
    (langue d'oc / Lengadòc, Gasconha, Provença...). No approximate
    transliteration: names are written in their authentic Occitan spelling.
    """

    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{prefix}} {{last_name}}",
        "{{first_name_female}} {{last_name}}-{{last_name}}",
        "{{first_name_female}}-{{first_name_female}} {{last_name}}",
    )

    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{prefix}} {{last_name}}",
        "{{first_name_male}} {{last_name}}-{{last_name}}",
        "{{first_name_male}}-{{first_name_male}} {{last_name}}",
    )

    formats = formats_male + formats_female

    first_names_male = (
        "Guilhèm",
        "Peire",
        "Bertran",
        "Ramon",
        "Raimon",
        "Bernat",
        "Arnaut",
        "Jaufre",
        "Aimeric",
        "Uc",
        "Pons",
        "Amalric",
        "Sicart",
        "Guiraut",
        "Gaucelm",
        "Peirol",
        "Marcabrun",
        "Rambaud",
        "Folco",
        "Centulh",
        "Gaston",
        "Roger",
        "Trencavel",
        "Elias",
        "Dalfin",
        "Joan",
        "Estève",
        "Miquèl",
        "Antòni",
        "Bertomieu",
        "Matieu",
        "Nicolau",
        "Andrieu",
        "Loís",
        "Frederic",
        "Jòrdi",
        "Marc",
        "Ramond",
        "Guilhèm-Ramon",
        "Aymeric",
        "Cabrit",
        "Peironèl",
    )

    first_names_female = (
        "Alienòr",
        "Esclarmonda",
        "Azalais",
        "Beatritz",
        "Ermengarda",
        "Garsenda",
        "Guilhelma",
        "Brunissenda",
        "Flamenca",
        "Loba",
        "Tibors",
        "Alamanda",
        "Sibilla",
        "Constança",
        "Blanca",
        "Comtessa",
        "Iseut",
        "Aude",
        "Berta",
        "Cerviera",
        "Estefania",
        "Peirona",
        "Ramona",
        "Joana",
        "Maria",
        "Anna",
        "Cristina",
        "Clara",
        "Elisabeta",
        "Isabèu",
        "Margalida",
        "Marguerida",
        "Ròsa",
        "Agnès",
        "Cecília",
        "Dieudona",
        "Fresca",
        "Bruna",
        "Na Castelosa",
        "Dòna",
        "Alazais",
        "Faidiva",
    )

    first_names = first_names_male + first_names_female

    last_names = (
        "Fabre",
        "Faure",
        "Bòsc",
        "Castèl",
        "Vidal",
        "Sabatièr",
        "Ferrièr",
        "Pastre",
        "Delmas",
        "Molin",
        "Camps",
        "Costa",
        "Riu",
        "Bòria",
        "Cazals",
        "Vernhet",
        "Solièr",
        "Puèg",
        "Serra",
        "Vabre",
        "Blanc",
        "Bru",
        "Nadal",
        "Barta",
        "Delrieu",
        "Espinassa",
        "Gasc",
        "Laval",
        "Rascol",
        "Combas",
        "Cabanas",
        "Milhau",
        "Aigas",
        "Bòrda",
        "Cortés",
        "Lafont",
        "Maurel",
        "Granièr",
        "Fornièr",
        "Ponç",
        "Salvat",
        "Nogaret",
        "Teulièr",
        "Peyre",
        "Segur",
        "Cambon",
        "Delpuèg",
        "Roqua",
        "Fontan",
        "Vaissièra",
    )

    prefixes = ("de", "del", "de la", "d'")
