from .. import Provider as PersonProvider


class Provider(PersonProvider):
    # Turkmen (Türkmen) names in the Latin script.

    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{last_name}} {{first_name_female}}",
        "{{prefix_female}} {{first_name_female}} {{last_name}}",
    )

    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{last_name}} {{first_name_male}}",
        "{{prefix_male}} {{first_name_male}} {{last_name}}",
    )

    formats = formats_male + formats_female

    first_names_male = (
        "Myrat",
        "Serdar",
        "Batyr",
        "Aman",
        "Berdi",
        "Gurban",
        "Nury",
        "Wepa",
        "Guwanç",
        "Merdan",
        "Kakageldi",
        "Meýlis",
        "Döwlet",
        "Begenç",
        "Yhlas",
        "Rejep",
        "Aşyr",
        "Çary",
        "Orazmämmet",
        "Annageldi",
        "Baýram",
        "Toýly",
        "Kerim",
        "Selim",
        "Halmyrat",
        "Perhat",
        "Şöhrat",
        "Yslam",
        "Maksat",
        "Nazar",
        "Kemal",
        "Rustem",
        "Yazmyrat",
        "Allaberdi",
        "Kadyr",
        "Öwezmyrat",
        "Sapar",
        "Gylyç",
        "Atajan",
        "Hojaguly",
        "Muhammet",
        "Röwşen",
        "Döwran",
        "Ýolaman",
        "Nurmuhammet",
        "Amanmyrat",
        "Baýmyrat",
        "Geldimyrat",
        "Suhan",
        "Yazgeldi",
    )

    first_names_female = (
        "Aýna",
        "Oguljeren",
        "Ogulnabat",
        "Maýa",
        "Bahar",
        "Jeren",
        "Güljemal",
        "Enejan",
        "Gözel",
        "Läle",
        "Dünýä",
        "Aýgül",
        "Selbi",
        "Ogulgerek",
        "Näzik",
        "Merjen",
        "Şasenem",
        "Aýbölek",
        "Gülşat",
        "Ogultäç",
        "Bagul",
        "Nurgözel",
        "Aýjemal",
        "Ogulbagt",
        "Jennet",
        "Mähri",
        "Aýsoltan",
        "Gunça",
        "Bossan",
        "Ogulsenem",
        "Gülnar",
        "Enegül",
        "Aknabat",
        "Oguljahan",
        "Sähra",
        "Ogulnar",
        "Ejegül",
        "Bibigül",
        "Näzli",
        "Gülbahar",
        "Maýsa",
        "Ýazgül",
        "Amangül",
        "Bägül",
        "Çynar",
        "Ogulbeg",
        "Enar",
        "Aýlar",
        "Gülälek",
        "Tawus",
    )

    first_names = first_names_male + first_names_female

    last_names = (
        "Myradow",
        "Berdiýew",
        "Gurbanow",
        "Amanow",
        "Nazarow",
        "Ataýew",
        "Çaryýew",
        "Rejepow",
        "Sapargeldiýew",
        "Hojaýew",
        "Meredow",
        "Annaýew",
        "Baýramow",
        "Kakabaýew",
        "Orazow",
        "Saparow",
        "Nuryýew",
        "Durdyýew",
        "Gylyjow",
        "Aşyrow",
        "Weliýew",
        "Seýidow",
        "Öwezow",
        "Halmyradow",
        "Yazmyradow",
        "Muhammedow",
        "Rozyýew",
        "Allaberdiýew",
        "Nepesow",
        "Garaýew",
        "Şyhyýew",
        "Taganow",
        "Begençow",
        "Toýlyýew",
        "Perhadow",
        "Kemalow",
        "Serdarow",
        "Guwançow",
        "Wepaýew",
        "Nurmuhammedow",
        "Atajanow",
        "Ýolamanow",
        "Döwranow",
        "Röwşenow",
        "Nyýazow",
        "Kakageldiýew",
        "Meýlisow",
        "Yhlasow",
    )

    prefixes_male = (
        "Jenap",
        "Dr.",
        "Prof.",
        "Mugallym",
    )

    prefixes_female = (
        "Hanym",
        "Dr.",
        "Prof.",
        "Mugallym",
    )

    prefixes = prefixes_male + prefixes_female
