from collections import OrderedDict

from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{prefix}} {{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}-{{last_name}}",
    )

    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{prefix}} {{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}-{{last_name}}",
    )

    formats = formats_male + formats_female

    # Authentic Māori (te reo Māori) given names, written in the Latin
    # script with macrons (tohutō) as used in Aotearoa New Zealand.
    first_names_male = (
        "Tāne",
        "Rangi",
        "Ngata",
        "Manaia",
        "Nikau",
        "Māui",
        "Tama",
        "Tāwhiri",
        "Rāwiri",
        "Hēmi",
        "Wiremu",
        "Hone",
        "Hoani",
        "Mikaere",
        "Pita",
        "Piripi",
        "Tipene",
        "Timoti",
        "Rāniera",
        "Anaru",
        "Paora",
        "Matiu",
        "Rōpata",
        "Ihaka",
        "Hōri",
        "Tāmati",
        "Nīkora",
        "Reweti",
        "Kingi",
        "Rewi",
        "Manu",
        "Kauri",
        "Rangatira",
        "Tū",
        "Karauria",
        "Manuka",
        "Taika",
        "Wī",
        "Tepene",
        "Hemi",
        "Rāpata",
        "Wetini",
        "Hakopa",
        "Eruera",
        "Tāwhai",
        "Aperahama",
        "Apirana",
        "Arama",
        "Ariki",
        "Eruini",
        "Hamiora",
        "Hataraka",
        "Henare",
        "Hepa",
        "Herewini",
        "Hira",
        "Hohepa",
        "Huatare",
        "Ihaia",
        "Irirangi",
        "Kahukura",
        "Kahutia",
        "Karepa",
        "Kereama",
        "Maaka",
        "Matenga",
        "Mohi",
        "Nāpera",
        "Nehemia",
        "Ngahiwi",
        "Ngakau",
        "Niko",
        "Noa",
        "Oriwa",
        "Paerata",
        "Panapa",
        "Paratene",
        "Patariki",
        "Peni",
        "Ranginui",
        "Rikirangi",
        "Riki",
        "Rongo",
        "Rongomai",
        "Ruka",
        "Rutene",
        "Taiaha",
        "Tainui",
        "Taipari",
        "Tamahou",
        "Tāwera",
        "Teina",
        "Toa",
        "Toko",
        "Tūmanako",
        "Tuari",
        "Tūmoana",
        "Wairere",
        "Waka",
        "Hare",
        "Kepa",
        "Wharenui",
        "Uenuku",
        "Tūmatauenga",
        "Māhaki",
        "Kahungunu",
        "Porourangi",
        "Tahu",
        "Paikea",
        "Tangaroa",
        "Whakatau",
        "Maru",
        "Kaha",
        "Manaaki",
        "Rāwaho",
        "Hakaraia",
        "Winiata",
        "Tāwhaki",
        "Rangitāne",
        "Poutini",
        "Erueti",
    )

    first_names_female = (
        "Aroha",
        "Kiri",
        "Ngaire",
        "Hine",
        "Mere",
        "Ripeka",
        "Hera",
        "Marama",
        "Anahera",
        "Ataahua",
        "Āwhina",
        "Moana",
        "Kahurangi",
        "Māia",
        "Miriama",
        "Rāwinia",
        "Ana",
        "Hinewai",
        "Huia",
        "Kahu",
        "Kōwhai",
        "Mihi",
        "Ngahuia",
        "Parekura",
        "Waimarie",
        "Whetū",
        "Amiria",
        "Erana",
        "Hana",
        "Keita",
        "Materoa",
        "Ngāpera",
        "Piata",
        "Roimata",
        "Tui",
        "Areta",
        "Hariata",
        "Meri",
        "Rāhera",
        "Wikitoria",
        "Rangimarie",
        "Manaia",
        "Tania",
        "Ngaio",
        "Puawai",
        "Aata",
        "Atarangi",
        "Harina",
        "Hinemoa",
        "Hineahuone",
        "Hinepau",
        "Hinerangi",
        "Hinewehi",
        "Hiria",
        "Hokimai",
        "Huhana",
        "Ihipera",
        "Irihapeti",
        "Kahupake",
        "Kaia",
        "Kararaina",
        "Kataraina",
        "Kirimātao",
        "Manawa",
        "Marino",
        "Matariki",
        "Matewai",
        "Mihiata",
        "Nganeko",
        "Ngatai",
        "Paretao",
        "Parehuia",
        "Paringatai",
        "Pania",
        "Pare",
        "Piki",
        "Rangimai",
        "Reipae",
        "Rewa",
        "Rongomaiwahine",
        "Ruia",
        "Terina",
        "Tia",
        "Titia",
        "Waina",
        "Waireti",
        "Waiora",
        "Waitohi",
        "Ataneta",
        "Hineata",
        "Karere",
        "Māreikura",
        "Ngawai",
        "Parehau",
        "Pirihira",
        "Rāita",
        "Rāwhiti",
        "Titewhai",
        "Waihora",
        "Whina",
        "Whakaruru",
        "Winika",
        "Roka",
        "Hēni",
        "Wai",
        "Ngahera",
        "Peti",
        "Rīhi",
        "Rūhia",
        "Hinetū",
        "Kiwa",
        "Manako",
        "Onehou",
        "Paremata",
        "Rāmeka",
        "Tāhau",
        "Tangiwai",
        "Te Ao",
        "Tūreiti",
        "Waiata",
        "Whetūmarama",
    )

    first_names = first_names_male + first_names_female

    # Authentic Māori whānau (family) names / surnames from iwi across
    # Aotearoa New Zealand.
    last_names = OrderedDict(
        (
            ("Ngata", 1.0),
            ("Pōmare", 1.0),
            ("Rātana", 1.0),
            ("Waititi", 1.0),
            ("Kīngi", 1.0),
            ("Mahuta", 1.0),
            ("Paki", 1.0),
            ("Te Heuheu", 1.0),
            ("Heke", 1.0),
            ("Kawiti", 1.0),
            ("Te Rauparaha", 1.0),
            ("Wētere", 1.0),
            ("Tomoana", 1.0),
            ("Kaa", 1.0),
            ("Tirikatene", 1.0),
            ("Parata", 1.0),
            ("Awatere", 1.0),
            ("Kohere", 1.0),
            ("Reweti", 1.0),
            ("Rangihau", 1.0),
            ("Puketapu", 1.0),
            ("Tuwhare", 1.0),
            ("Ruru", 1.0),
            ("Kereopa", 1.0),
            ("Te Kani", 1.0),
            ("Nikora", 1.0),
            ("Waaka", 1.0),
            ("Tarei", 1.0),
            ("Wineera", 1.0),
            ("Hape", 1.0),
            ("Rangi", 1.0),
            ("Katene", 1.0),
            ("Ihimaera", 1.0),
            ("Mataira", 1.0),
            ("Karetai", 1.0),
            ("Taiaroa", 1.0),
            ("Pere", 1.0),
            ("Manuera", 1.0),
            ("Tukaki", 1.0),
            ("Wikaira", 1.0),
            ("Whata", 1.0),
            ("Ropiha", 1.0),
            ("Rerekura", 1.0),
            ("Te Kanawa", 1.0),
            ("Tūpara", 1.0),
            ("Ngaruhe", 1.0),
            ("Hetaraka", 1.0),
            ("Te Amo", 1.0),
            ("Te Aika", 1.0),
            ("Te Ua", 1.0),
            ("Te Puni", 1.0),
            ("Te Wharau", 1.0),
            ("Ngaropo", 1.0),
            ("Poananga", 1.0),
            ("Rangihuna", 1.0),
            ("Wharepapa", 1.0),
            ("Whaanga", 1.0),
            ("Ratahi", 1.0),
            ("Hoterene", 1.0),
            ("Te Whaiti", 1.0),
            ("Ngāwati", 1.0),
            ("Te Rangikaheke", 1.0),
            ("Kereru", 1.0),
            ("Manihera", 1.0),
            ("Te Awekotuku", 1.0),
            ("Te Kaawa", 1.0),
            ("Wanoa", 1.0),
            ("Poata", 1.0),
            ("Te Ohaere", 1.0),
            ("Ngawaka", 1.0),
            ("Rakena", 1.0),
            ("Waretini", 1.0),
            ("Te Moana", 1.0),
            ("Ihaka", 1.0),
            ("Hakaraia", 1.0),
            ("Pohatu", 1.0),
            ("Waenga", 1.0),
            ("Tamihana", 1.0),
            ("Te Rangi", 1.0),
            ("Ngamoki", 1.0),
            ("Rikihana", 1.0),
            ("Te Whata", 1.0),
            ("Panapa", 1.0),
            ("Waihi", 1.0),
            ("Te Hau", 1.0),
            ("Rāpana", 1.0),
            ("Whakataka", 1.0),
            ("Ngaia", 1.0),
            ("Te Aho", 1.0),
            ("Te Kata", 1.0),
            ("Whakarua", 1.0),
            ("Tuterangi", 1.0),
            ("Te Wano", 1.0),
            ("Ngahuka", 1.0),
            ("Tuhaka", 1.0),
            ("Te Nana", 1.0),
            ("Te Ariki", 1.0),
            ("Whakarongo", 1.0),
            ("Papuni", 1.0),
            ("Te Uira", 1.0),
            ("Te Riaki", 1.0),
            ("Kaipara", 1.0),
            ("Ngatai", 1.0),
            ("Te Whetū", 1.0),
            ("Toroa", 1.0),
            ("Nuku", 1.0),
            ("Tautari", 1.0),
            ("Hokianga", 1.0),
            ("Te Wehi", 1.0),
            ("Mokomoko", 1.0),
            ("Rongo", 1.0),
            ("Te Rire", 1.0),
            ("Herewini", 1.0),
            ("Te Puea", 1.0),
            ("Te Uru", 1.0),
            ("Whitiora", 1.0),
            ("Te Kire", 1.0),
            ("Maniapoto", 1.0),
            ("Te Weu", 1.0),
            ("Rāwhiti", 1.0),
            ("Ngamotu", 1.0),
            ("Te Puke", 1.0),
        )
    )

    # Māori honorifics / terms of respect used before a name.
    prefixes = ("Matua", "Whaea", "Koro", "Kuia", "Tā", "Rangatira")
