from collections import OrderedDict

from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{prefix}} {{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}-{{last_name}}",
    )

    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{prefix}} {{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}-{{last_name}}",
    )

    formats = formats_male + formats_female

    # Authentic Māori (te reo Māori) given names, written in the Latin
    # script with macrons (tohutō) as used in Aotearoa New Zealand.
    first_names_male = (
        "Tāne",
        "Rangi",
        "Ngata",
        "Manaia",
        "Nikau",
        "Māui",
        "Tama",
        "Tāwhiri",
        "Rāwiri",
        "Hēmi",
        "Wiremu",
        "Hone",
        "Hoani",
        "Mikaere",
        "Pita",
        "Piripi",
        "Tipene",
        "Timoti",
        "Rāniera",
        "Anaru",
        "Paora",
        "Matiu",
        "Rōpata",
        "Ihaka",
        "Hōri",
        "Tāmati",
        "Nīkora",
        "Reweti",
        "Kingi",
        "Rewi",
        "Manu",
        "Kauri",
        "Rangatira",
        "Tū",
        "Karauria",
        "Manuka",
        "Taika",
        "Wī",
        "Tepene",
        "Hemi",
        "Rāpata",
        "Wetini",
        "Hakopa",
        "Eruera",
        "Tāwhai",
    )

    first_names_female = (
        "Aroha",
        "Kiri",
        "Ngaire",
        "Hine",
        "Mere",
        "Ripeka",
        "Hera",
        "Marama",
        "Anahera",
        "Ataahua",
        "Āwhina",
        "Moana",
        "Kahurangi",
        "Māia",
        "Miriama",
        "Rāwinia",
        "Ana",
        "Hinewai",
        "Huia",
        "Kahu",
        "Kōwhai",
        "Mihi",
        "Ngahuia",
        "Parekura",
        "Waimarie",
        "Whetū",
        "Amiria",
        "Erana",
        "Hana",
        "Keita",
        "Materoa",
        "Ngāpera",
        "Piata",
        "Roimata",
        "Tui",
        "Areta",
        "Hariata",
        "Meri",
        "Rāhera",
        "Wikitoria",
        "Rangimarie",
        "Manaia",
        "Tania",
        "Ngaio",
        "Puawai",
    )

    first_names = first_names_male + first_names_female

    # Authentic Māori whānau (family) names / surnames from iwi across
    # Aotearoa New Zealand.
    last_names = OrderedDict(
        (
            ("Ngata", 1.0),
            ("Pōmare", 1.0),
            ("Rātana", 1.0),
            ("Waititi", 1.0),
            ("Kīngi", 1.0),
            ("Mahuta", 1.0),
            ("Paki", 1.0),
            ("Te Heuheu", 1.0),
            ("Heke", 1.0),
            ("Kawiti", 1.0),
            ("Te Rauparaha", 1.0),
            ("Wētere", 1.0),
            ("Tomoana", 1.0),
            ("Kaa", 1.0),
            ("Tirikatene", 1.0),
            ("Parata", 1.0),
            ("Awatere", 1.0),
            ("Kohere", 1.0),
            ("Reweti", 1.0),
            ("Rangihau", 1.0),
            ("Puketapu", 1.0),
            ("Tuwhare", 1.0),
            ("Ruru", 1.0),
            ("Kereopa", 1.0),
            ("Te Kani", 1.0),
            ("Nikora", 1.0),
            ("Waaka", 1.0),
            ("Tarei", 1.0),
            ("Wineera", 1.0),
            ("Hape", 1.0),
            ("Rangi", 1.0),
            ("Katene", 1.0),
            ("Ihimaera", 1.0),
            ("Mataira", 1.0),
            ("Karetai", 1.0),
            ("Taiaroa", 1.0),
            ("Pere", 1.0),
            ("Manuera", 1.0),
            ("Tukaki", 1.0),
            ("Wikaira", 1.0),
            ("Whata", 1.0),
            ("Ropiha", 1.0),
            ("Rerekura", 1.0),
            ("Te Kanawa", 1.0),
        )
    )

    # Māori honorifics / terms of respect used before a name.
    prefixes = ("Matua", "Whaea", "Koro", "Kuia", "Tā", "Rangatira")
