from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{prefix_male}} {{first_name_male}} {{last_name}}",
        "{{first_name_male}}",
    )

    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{prefix_female}} {{first_name_female}} {{last_name}}",
        "{{first_name_female}}",
    )

    formats = formats_male + formats_female

    # Authentic Javanese (Basa Jawa) given names written in the Latin script.
    first_names_male = (
        "Bagus",
        "Joko",
        "Djoko",
        "Slamet",
        "Wibowo",
        "Sutrisno",
        "Sujarwo",
        "Purnomo",
        "Widodo",
        "Hartono",
        "Bambang",
        "Untung",
        "Suyono",
        "Prasetyo",
        "Nugroho",
        "Wahyudi",
        "Gunawan",
        "Setiawan",
        "Prabowo",
        "Suryono",
        "Waluyo",
        "Suparno",
        "Cahyono",
        "Darmawan",
        "Handoko",
        "Iswanto",
        "Basuki",
        "Riyanto",
        "Susilo",
        "Teguh",
        "Wisnu",
        "Danang",
        "Guntur",
        "Bayu",
        "Wahyu",
        "Anom",
        "Marsudi",
        "Sukarno",
        "Sardjono",
        "Marno",
        "Ngadiman",
        "Painan",
        "Suradi",
        "Warsito",
        "Sumadi",
        "Giyanto",
        "Parjono",
        "Sunarto",
    )

    first_names_female = (
        "Sri",
        "Wulan",
        "Ratih",
        "Sekar",
        "Endang",
        "Sumarni",
        "Lestari",
        "Rukmini",
        "Sulastri",
        "Warsini",
        "Partini",
        "Suparti",
        "Rahayu",
        "Mulyani",
        "Wahyuni",
        "Handayani",
        "Utami",
        "Ratna",
        "Dewi",
        "Ayu",
        "Retno",
        "Murtini",
        "Suryani",
        "Larasati",
        "Kartika",
        "Astuti",
        "Sundari",
        "Winarti",
        "Ningsih",
        "Purwanti",
        "Sukesi",
        "Sumiyati",
        "Painem",
        "Tumini",
        "Ngatini",
        "Suminten",
        "Prihatin",
        "Marsinah",
        "Wagiyem",
        "Sutinah",
        "Yatmi",
        "Darmi",
        "Menik",
        "Sri Lestari",
        "Dwi Astuti",
    )

    first_names = first_names_male + first_names_female

    # Authentic Javanese family/clan names in the Latin script.
    last_names = (
        "Wibowo",
        "Wijaya",
        "Kusuma",
        "Santoso",
        "Susanto",
        "Saputra",
        "Prasetya",
        "Nugroho",
        "Purnama",
        "Utomo",
        "Hartanto",
        "Setiawan",
        "Gunawan",
        "Suryanto",
        "Wardana",
        "Pratama",
        "Handoyo",
        "Wicaksono",
        "Prabowo",
        "Sudarsono",
        "Sumarsono",
        "Widagdo",
        "Suryadi",
        "Martono",
        "Sugiharto",
        "Waskito",
        "Sasongko",
        "Pamungkas",
        "Anggoro",
        "Baskoro",
        "Mahendra",
        "Suryaputra",
        "Wardoyo",
        "Puspito",
        "Cokrowidjojo",
        "Mangkusasmito",
        "Notonegoro",
        "Adiningrat",
        "Mangunkusumo",
        "Sastrowardoyo",
        "Wiryadi",
        "Sudibyo",
        "Broto",
        "Kartodihardjo",
        "Padmanegara",
        "Suryaningrat",
    )

    # Javanese honorifics and titles.
    prefixes_male = (
        "Mas",
        "Raden",
        "Raden Mas",
        "Bapak",
        "Ki",
        "Kyai",
        "Den",
    )

    prefixes_female = (
        "Mbak",
        "Raden Ajeng",
        "Raden Roro",
        "Ibu",
        "Nyi",
    )

    prefixes = prefixes_male + prefixes_female
