from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}-{{last_name}}",
        "{{prefix_female}} {{first_name_female}} {{last_name}}",
        "{{prefix_female}} {{first_name_female}} {{last_name}}",
    )

    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}-{{last_name}}",
        "{{prefix_male}} {{first_name_male}} {{last_name}}",
        "{{prefix_male}} {{first_name_male}} {{last_name}}",
    )

    formats = formats_female + formats_male

    # Authentic Breton (brezhoneg) given names
    first_names_male = (
        "Yann",
        "Erwan",
        "Erwann",
        "Gwenaël",
        "Loeiz",
        "Fañch",
        "Herve",
        "Hervé",
        "Job",
        "Maël",
        "Ronan",
        "Tangi",
        "Tanguy",
        "Gireg",
        "Judikael",
        "Alan",
        "Envel",
        "Goulven",
        "Padrig",
        "Youenn",
        "Riwal",
        "Efflam",
        "Konan",
        "Tudwal",
        "Gildas",
        "Meven",
        "Salaün",
        "Deniel",
        "Brieg",
        "Weltaz",
        "Nedeleg",
        "Gwenole",
        "Kaourantin",
        "Yannig",
        "Bleiz",
        "Kadeg",
        "Denez",
        "Fragan",
        "Maodez",
        "Neventer",
        "Paol",
        "Tremeur",
        "Kadou",
        "Yeun",
        "Brendan",
        "Aodren",
        "Alar",
        "Alberzh",
        "Andrev",
        "Aogust",
        "Arzhel",
        "Arzhur",
        "Benead",
        "Bernez",
        "Bran",
        "Budog",
        "Devi",
        "Divi",
        "Edern",
        "Elouan",
        "Envael",
        "Erwanig",
        "Ewen",
        "Even",
        "Gaël",
        "Glaoda",
        "Goneri",
        "Gorvan",
        "Gradlon",
        "Gwendal",
        "Gwenneg",
        "Gwennin",
        "Gwilherm",
        "Herle",
        "Herri",
        "Iltud",
        "Jakez",
        "Jaoua",
        "Jestin",
        "Jorj",
        "Kado",
        "Kadvael",
        "Karadeg",
        "Kilian",
        "Kirio",
        "Klaod",
        "Konogan",
        "Konvael",
        "Korneli",
        "Loïc",
        "Loïg",
        "Lom",
        "Malo",
        "Maodan",
        "Marzhin",
        "Mazhe",
        "Mikael",
        "Milio",
        "Morvan",
        "Nominoe",
        "Padern",
        "Pêr",
        "Peran",
        "Pol",
        "Primael",
        "Rimael",
        "Rioc",
        "Riwallon",
        "Roparzh",
        "Servan",
        "Sezni",
        "Steven",
        "Sulian",
        "Tadeg",
        "Tegoneg",
        "Tual",
        "Tudi",
        "Turiau",
        "Urfol",
        "Winoc",
        "Yann-Bêr",
        "Yannick",
        "Yaouen",
    )

    first_names_female = (
        "Anna",
        "Katell",
        "Nolwenn",
        "Rozenn",
        "Aziliz",
        "Gwenn",
        "Enora",
        "Soazig",
        "Mona",
        "Maïwenn",
        "Gaïd",
        "Loeiza",
        "Mari",
        "Marivon",
        "Perrine",
        "Riwanon",
        "Tereza",
        "Levenez",
        "Gwenaëlle",
        "Klervi",
        "Annaig",
        "Solenn",
        "Aourell",
        "Aela",
        "Bleuenn",
        "Azenor",
        "Berc'hed",
        "Lenaig",
        "Onenn",
        "Gwenola",
        "Katarin",
        "Morwenna",
        "Servane",
        "Sterenn",
        "Yuna",
        "Awen",
        "Maela",
        "Naig",
        "Rozela",
        "Nolwennig",
        "Malou",
        "Herveline",
        "Deniela",
        "Loeizig",
        "Aouregan",
        "Argantael",
        "Alanig",
        "Anaelle",
        "Andrea",
        "Barba",
        "Brendana",
        "Briaga",
        "Brigite",
        "Delina",
        "Elen",
        "Elin",
        "Elouana",
        "Enez",
        "Eozenn",
        "Gaela",
        "Gladez",
        "Glwadys",
        "Gwendolina",
        "Gwennig",
        "Gwennina",
        "Gwennora",
        "Heodez",
        "Izold",
        "Jenovefa",
        "Judikaela",
        "Kanna",
        "Karantez",
        "Katarina",
        "Katarinig",
        "Katellig",
        "Klaoda",
        "Klervia",
        "Koupaia",
        "Lena",
        "Loeizaig",
        "Loeva",
        "Louisa",
        "Madalen",
        "Maiana",
        "Malaig",
        "Marc'harid",
        "Margodig",
        "Mariana",
        "Marjolen",
        "Melloni",
        "Mikaela",
        "Morgana",
        "Morgane",
        "Nevenoe",
        "Ninnog",
        "Noluenn",
        "Nolwena",
        "Oanez",
        "Orlane",
        "Padrezig",
        "Perrina",
        "Plesou",
        "Riwana",
        "Riwanez",
        "Ronana",
        "Rozennig",
        "Seva",
        "Sinaig",
        "Soizig",
        "Solena",
        "Steredenn",
        "Sterennig",
        "Talwenn",
        "Tanwenn",
        "Tereseg",
        "Tifenn",
        "Tina",
        "Trifin",
        "Ugana",
        "Uriell",
        "Yannaig",
        "Youna",
        "Yseult",
    )

    first_names = first_names_male + first_names_female

    # Common Breton (brezhoneg) surnames
    last_names = (
        "Le Bris",
        "Le Gall",
        "Le Goff",
        "Le Roy",
        "Le Guen",
        "Le Bihan",
        "Le Corre",
        "Le Floch",
        "Le Braz",
        "Le Duff",
        "Le Berre",
        "Le Moal",
        "Le Guennec",
        "Le Meur",
        "Le Coz",
        "Le Du",
        "Le Lann",
        "Le Guilloux",
        "Tanguy",
        "Prigent",
        "Riou",
        "Salaün",
        "Jaffré",
        "Cariou",
        "Kervella",
        "Guéguen",
        "Kermarrec",
        "Quéméner",
        "Nédélec",
        "Guyomarc'h",
        "Herviou",
        "Bourhis",
        "Cadiou",
        "Kerguelen",
        "Kerbrat",
        "Kervadec",
        "Kernévez",
        "Penven",
        "Perrot",
        "Pennec",
        "Goasdoué",
        "Kerangall",
        "Trébaol",
        "Corlay",
        "Abgrall",
        "Le Gac",
        "Le Guern",
        "Le Gallo",
        "Le Hénaff",
        "Le Pape",
        "Le Provost",
        "Le Saux",
        "Le Tallec",
        "Le Dantec",
        "Le Guyader",
        "Le Bras",
        "Le Bail",
        "Le Bec",
        "Le Roux",
        "Le Fur",
        "Le Doze",
        "Le Faou",
        "Le Foll",
        "Le Gonidec",
        "Le Grand",
        "Le Guével",
        "Le Hir",
        "Le Jeune",
        "Le Loarer",
        "Le Mao",
        "Le Mercier",
        "Le Naour",
        "Le Priol",
        "Le Quéré",
        "Le Rest",
        "Le Sommer",
        "Le Trocquer",
        "Le Viol",
        "Le Bloas",
        "Le Deunff",
        "Le Nézet",
        "Le Meudec",
        "Le Guellec",
        "Le Corvec",
        "Kerbaol",
        "Kerdraon",
        "Kerhervé",
        "Kerjean",
        "Kerleau",
        "Kerloc'h",
        "Kerneis",
        "Kerneur",
        "Kerivel",
        "Kerouanton",
        "Kervran",
        "Kerzerho",
        "Keravec",
        "Guillou",
        "Gourvennec",
        "Guivarc'h",
        "Guillerm",
        "Goasguen",
        "Floc'h",
        "Hascoët",
        "Helias",
        "Hénaff",
        "Jézéquel",
        "Kloareg",
        "Madec",
        "Mao",
        "Marec",
        "Merour",
        "Morvan",
        "Nicol",
        "Pichon",
        "Postic",
        "Quémère",
        "Rannou",
        "Rolland",
        "Séveno",
        "Stéphan",
        "Tromeur",
        "Uguen",
    )

    prefixes_female = ("Itron", "Dimezell")
    prefixes_male = ("Aotrou",)

    prefixes = prefixes_female + prefixes_male
