from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}-{{last_name}}",
        "{{prefix_female}} {{first_name_female}} {{last_name}}",
        "{{prefix_female}} {{first_name_female}} {{last_name}}",
    )

    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}-{{last_name}}",
        "{{prefix_male}} {{first_name_male}} {{last_name}}",
        "{{prefix_male}} {{first_name_male}} {{last_name}}",
    )

    formats = formats_female + formats_male

    # Authentic Welsh (Cymraeg) given names
    first_names_male = (
        "Dafydd",
        "Rhys",
        "Iwan",
        "Aled",
        "Gareth",
        "Gwilym",
        "Emyr",
        "Ieuan",
        "Owain",
        "Geraint",
        "Huw",
        "Dylan",
        "Cai",
        "Iestyn",
        "Bleddyn",
        "Cadwaladr",
        "Caradog",
        "Cynan",
        "Deiniol",
        "Eifion",
        "Emlyn",
        "Emrys",
        "Gwyn",
        "Hywel",
        "Idris",
        "Ifor",
        "Illtud",
        "Ioan",
        "Islwyn",
        "Llewelyn",
        "Llywelyn",
        "Madog",
        "Maredudd",
        "Meirion",
        "Meurig",
        "Morgan",
        "Osian",
        "Padarn",
        "Peredur",
        "Prys",
        "Rhodri",
        "Rhydian",
        "Rhydderch",
        "Sion",
        "Steffan",
        "Taliesin",
        "Trystan",
        "Tudur",
        "Wyn",
        "Alun",
        "Arwel",
        "Berwyn",
        "Carwyn",
        "Celyn",
        "Dewi",
        "Eurig",
        "Gethin",
        "Guto",
        "Heddwyn",
        "Ianto",
        "Lloyd",
        "Macsen",
        "Tomos",
    )

    first_names_female = (
        "Gwenllian",
        "Ffion",
        "Seren",
        "Cerys",
        "Angharad",
        "Bethan",
        "Carys",
        "Catrin",
        "Delyth",
        "Eleri",
        "Elin",
        "Enfys",
        "Esyllt",
        "Gwen",
        "Gwenda",
        "Gwyneth",
        "Heledd",
        "Lowri",
        "Mair",
        "Mali",
        "Manon",
        "Megan",
        "Meinir",
        "Mererid",
        "Myfanwy",
        "Nerys",
        "Nia",
        "Olwen",
        "Rhian",
        "Rhiannon",
        "Rhonwen",
        "Sian",
        "Sioned",
        "Tegan",
        "Tegwen",
        "Aeronwy",
        "Alaw",
        "Aneira",
        "Arianwen",
        "Aures",
        "Blodwen",
        "Branwen",
        "Bronwen",
        "Buddug",
        "Cari",
        "Ceinwen",
        "Cordelia",
        "Dwynwen",
        "Efa",
        "Eiddwen",
        "Eira",
        "Eirlys",
        "Elenid",
        "Ffraid",
        "Glenys",
        "Glesni",
        "Gwenno",
        "Haf",
        "Lois",
        "Lynwen",
        "Mabli",
        "Marged",
        "Non",
        "Sara",
    )

    first_names = first_names_male + first_names_female

    # Common Welsh (Cymraeg) surnames
    last_names = (
        "Jones",
        "Williams",
        "Davies",
        "Evans",
        "Thomas",
        "Roberts",
        "Hughes",
        "Lewis",
        "Owen",
        "Morgan",
        "Griffiths",
        "Edwards",
        "Rees",
        "Price",
        "Phillips",
        "Powell",
        "Bevan",
        "Bowen",
        "Vaughan",
        "James",
        "Pritchard",
        "Prosser",
        "Probert",
        "Meredith",
        "Lloyd",
        "Llewelyn",
        "Pugh",
        "Parry",
        "Prydderch",
        "Maddocks",
        "Bythell",
        "Cadwaladr",
        "Caradog",
        "Gruffudd",
        "Gwynn",
        "Havard",
        "Kyffin",
        "Mostyn",
        "Nanney",
        "Wynne",
        "Beynon",
        "Cadwallader",
        "Gethin",
        "Gough",
        "Gwilym",
        "Heddwyn",
        "Hywel",
        "Iestyn",
        "Ithel",
        "Maelor",
        "Penry",
        "Tudor",
        "Trahaearn",
        "Wogan",
        "ap Rhys",
        "ap Dafydd",
        "ap Gwilym",
        "ap Hywel",
        "ap Iwan",
        "ap Llywelyn",
        "ap Morgan",
        "ferch Owain",
    )

    prefixes_female = ("Mrs", "Ms", "Miss", "Dr", "Foneddiges", "Y Barchedig")
    prefixes_male = ("Mr", "Dr", "Syr", "Y Parchedig", "Athro")

    prefixes = prefixes_female + prefixes_male
