from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_male = (
        "{{first_name_male}} {{last_name}} {{last_name}}",
        "{{first_name_male}} {{last_name}} {{last_name}}",
        "{{first_name_male}} {{last_name}} {{last_name}}",
        "{{first_name_male}} {{last_name}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{prefix}} {{last_name}}",
        "{{first_name_male}} {{last_name}}-{{last_name}}",
        "{{first_name_male}} {{first_name_male}} {{last_name}} {{last_name}}",
    )

    formats_female = (
        "{{first_name_female}} {{last_name}} {{last_name}}",
        "{{first_name_female}} {{last_name}} {{last_name}}",
        "{{first_name_female}} {{last_name}} {{last_name}}",
        "{{first_name_female}} {{last_name}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{prefix}} {{last_name}}",
        "{{first_name_female}} {{last_name}}-{{last_name}}",
        "{{first_name_female}} {{first_name_female}} {{last_name}} {{last_name}}",
    )

    formats = formats_male + formats_female

    # Authentic Galician (galego) male given names.
    first_names_male = (
        "Brais",
        "Xoán",
        "Xoel",
        "Antón",
        "Anxo",
        "Breogán",
        "Iago",
        "Martiño",
        "Roi",
        "Xabier",
        "Xosé",
        "Xurxo",
        "Xacobe",
        "Uxío",
        "Xaquín",
        "Fiz",
        "Paio",
        "Cibrán",
        "Lois",
        "Xerardo",
        "Estevo",
        "Xesús",
        "Denís",
        "Marcos",
        "Rubén",
        "Adrián",
        "Diego",
        "Hugo",
        "Ramón",
        "Bieito",
        "Amaro",
        "Xián",
        "Nuno",
        "Manuel",
        "Andrés",
        "Xacinto",
        "Xoaquín",
        "Bras",
        "Roxelio",
        "Alexandre",
        "Antonio",
        "Carlos",
        "Fernando",
        "Pedro",
        "Xavier",
    )

    # Authentic Galician (galego) female given names.
    first_names_female = (
        "Antía",
        "Uxía",
        "Sabela",
        "Iria",
        "Noa",
        "Aldara",
        "Lúa",
        "Rosalía",
        "Icía",
        "Comba",
        "Olalla",
        "Tareixa",
        "Minia",
        "Branca",
        "Xoana",
        "Estela",
        "Mariña",
        "Candela",
        "Maruxa",
        "Anxos",
        "Dores",
        "Carme",
        "Lucía",
        "Noela",
        "Alba",
        "Adega",
        "Erea",
        "Nerea",
        "Xiana",
        "Antela",
        "Roxelia",
        "Amara",
        "Paula",
        "Laura",
        "Fátima",
        "Aurora",
        "Cándida",
        "Xela",
        "Ledicia",
        "Mencía",
        "Elba",
        "Cristina",
        "Noelia",
        "Sara",
        "Sonia",
    )

    # Common Galician surnames.
    last_names = (
        "Castro",
        "Rodríguez",
        "Fernández",
        "González",
        "Vázquez",
        "Pérez",
        "Álvarez",
        "Blanco",
        "García",
        "López",
        "Gómez",
        "Iglesias",
        "Souto",
        "Otero",
        "Ferreiro",
        "Seoane",
        "Barreiro",
        "Currás",
        "Filgueira",
        "Rial",
        "Meixide",
        "Lameiro",
        "Nogueira",
        "Carballo",
        "Lorenzo",
        "Vilar",
        "Quintáns",
        "Rivas",
        "Freire",
        "Neira",
        "Bugallo",
        "Losada",
        "Piñeiro",
        "Regueira",
        "Doval",
        "Feijóo",
        "Beiras",
        "Cela",
        "Novoa",
        "Paz",
        "Vidal",
        "Cores",
        "Deán",
        "Miragaia",
        "Xesteira",
        "Portela",
        "Ledo",
        "Randulfe",
    )

    prefixes = ("de", "do", "da")
