from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{prefix_male}} {{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{first_name_male}} {{last_name}}",
    )

    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{prefix_female}} {{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{first_name_female}} {{last_name}}",
    )

    formats = formats_male + formats_female

    # Authentic Sundanese (basa Sunda) male given names, Latin script.
    first_names_male = (
        "Asep",
        "Ujang",
        "Jajang",
        "Dadang",
        "Cecep",
        "Yayan",
        "Dede",
        "Nana",
        "Iwan",
        "Maman",
        "Otong",
        "Encep",
        "Aep",
        "Aceng",
        "Enjang",
        "Oman",
        "Tatang",
        "Entis",
        "Aang",
        "Deden",
        "Kosasih",
        "Sobandi",
        "Suryana",
        "Rohman",
        "Wawan",
        "Nandang",
        "Undang",
        "Emod",
        "Rustandi",
        "Suhaya",
        "Elang",
        "Karta",
        "Warsa",
        "Uu",
        "Endang",
        "Ganjar",
        "Yaya",
        "Sukmana",
        "Rukmana",
        "Sanusi",
        "Aki",
        "Enjum",
        "Tarya",
        "Wardaya",
        "Jaka",
    )

    # Authentic Sundanese (basa Sunda) female given names, Latin script.
    first_names_female = (
        "Euis",
        "Neng",
        "Cucu",
        "Imas",
        "Ai",
        "Ela",
        "Eli",
        "Enok",
        "Ineu",
        "Iis",
        "Titin",
        "Nining",
        "Nunung",
        "Yoyoh",
        "Ecin",
        "Icih",
        "Odah",
        "Popon",
        "Wiwin",
        "Nunuy",
        "Teti",
        "Tati",
        "Eneng",
        "Eti",
        "Elis",
        "Cicih",
        "Onah",
        "Enah",
        "Dedeh",
        "Kokom",
        "Iyah",
        "Yuyun",
        "Enung",
        "Titih",
        "Cacih",
        "Nyai",
        "Lilis",
        "Yoyom",
        "Warsih",
        "Sumiati",
        "Emin",
        "Uneng",
        "Rasti",
        "Ningrum",
        "Aisah",
    )

    # Sundanese family / second names, Latin script. Many end in the
    # traditional -wijaya, -atmaja, -dinata, -nagara, -kusumah suffixes.
    last_names = (
        "Suryana",
        "Wijaya",
        "Nugraha",
        "Permana",
        "Kusmana",
        "Wardana",
        "Gunawan",
        "Setiawan",
        "Kurniawan",
        "Hidayat",
        "Suherman",
        "Sutisna",
        "Sukmana",
        "Rukmana",
        "Ramdani",
        "Ramdhan",
        "Firmansyah",
        "Hermawan",
        "Saepuloh",
        "Nurjaman",
        "Somantri",
        "Kartawijaya",
        "Wiratama",
        "Purnama",
        "Sunarya",
        "Mulyana",
        "Suryadi",
        "Kosasih",
        "Sobari",
        "Sanjaya",
        "Prawira",
        "Wiranata",
        "Karyana",
        "Sasmita",
        "Prayoga",
        "Nataatmaja",
        "Suwanda",
        "Kartadinata",
        "Wangsaatmaja",
        "Adiwijaya",
        "Wiradinata",
        "Tanuwijaya",
        "Natakusumah",
        "Prawiranagara",
        "Suryaputra",
    )

    prefixes = (
        "Kang",
        "Ceu",
        "Mang",
        "Ambu",
        "Abah",
        "Nyi",
        "Aa",
        "Teteh",
    )
