from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}-{{last_name}}",
        "{{prefix_female}} {{first_name_female}} {{last_name}}",
        "{{prefix_female}} {{first_name_female}} {{last_name}}",
    )

    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}-{{last_name}}",
        "{{prefix_male}} {{first_name_male}} {{last_name}}",
        "{{prefix_male}} {{first_name_male}} {{last_name}}",
    )

    formats = formats_female + formats_male

    # Authentic Breton (brezhoneg) given names
    first_names_male = (
        "Yann",
        "Erwan",
        "Erwann",
        "Gwenaël",
        "Loeiz",
        "Fañch",
        "Herve",
        "Hervé",
        "Job",
        "Maël",
        "Ronan",
        "Tangi",
        "Tanguy",
        "Gireg",
        "Judikael",
        "Alan",
        "Envel",
        "Goulven",
        "Padrig",
        "Youenn",
        "Riwal",
        "Efflam",
        "Konan",
        "Tudwal",
        "Gildas",
        "Meven",
        "Salaün",
        "Deniel",
        "Brieg",
        "Weltaz",
        "Nedeleg",
        "Gwenole",
        "Kaourantin",
        "Yannig",
        "Bleiz",
        "Kadeg",
        "Denez",
        "Fragan",
        "Maodez",
        "Neventer",
        "Paol",
        "Tremeur",
        "Kadou",
        "Yeun",
        "Brendan",
    )

    first_names_female = (
        "Anna",
        "Katell",
        "Nolwenn",
        "Rozenn",
        "Aziliz",
        "Gwenn",
        "Enora",
        "Soazig",
        "Mona",
        "Maïwenn",
        "Gaïd",
        "Loeiza",
        "Mari",
        "Marivon",
        "Perrine",
        "Riwanon",
        "Tereza",
        "Levenez",
        "Gwenaëlle",
        "Klervi",
        "Annaig",
        "Solenn",
        "Aourell",
        "Aela",
        "Bleuenn",
        "Azenor",
        "Berc'hed",
        "Lenaig",
        "Onenn",
        "Gwenola",
        "Katarin",
        "Morwenna",
        "Servane",
        "Sterenn",
        "Yuna",
        "Awen",
        "Maela",
        "Naig",
        "Rozela",
        "Nolwennig",
        "Malou",
        "Herveline",
        "Deniela",
        "Loeizig",
        "Aouregan",
    )

    first_names = first_names_male + first_names_female

    # Common Breton (brezhoneg) surnames
    last_names = (
        "Le Bris",
        "Le Gall",
        "Le Goff",
        "Le Roy",
        "Le Guen",
        "Le Bihan",
        "Le Corre",
        "Le Floch",
        "Le Braz",
        "Le Duff",
        "Le Berre",
        "Le Moal",
        "Le Guennec",
        "Le Meur",
        "Le Coz",
        "Le Du",
        "Le Lann",
        "Le Guilloux",
        "Tanguy",
        "Prigent",
        "Riou",
        "Salaün",
        "Jaffré",
        "Cariou",
        "Kervella",
        "Guéguen",
        "Kermarrec",
        "Quéméner",
        "Nédélec",
        "Guyomarc'h",
        "Herviou",
        "Bourhis",
        "Cadiou",
        "Kerguelen",
        "Kerbrat",
        "Kervadec",
        "Kernévez",
        "Penven",
        "Perrot",
        "Pennec",
        "Goasdoué",
        "Kerangall",
        "Trébaol",
        "Corlay",
        "Abgrall",
    )

    prefixes_female = ("Itron", "Dimezell")
    prefixes_male = ("Aotrou",)

    prefixes = prefixes_female + prefixes_male
