from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{prefix}} {{first_name_male}} {{last_name}}",
    )

    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{prefix}} {{first_name_female}} {{last_name}}",
    )

    formats = formats_male + formats_female

    # Authentieke Afrikaanse manlike voorname
    first_names_male = (
        "Pieter",
        "Johan",
        "Jan",
        "Willem",
        "Hendrik",
        "Cornelius",
        "Frederik",
        "Andries",
        "Gerhard",
        "Stephanus",
        "Petrus",
        "Jacobus",
        "Christiaan",
        "Barend",
        "Dirk",
        "Kobus",
        "Danie",
        "Riaan",
        "Ruan",
        "Divan",
        "Wynand",
        "Schalk",
        "Theunis",
        "Marius",
        "Hannes",
        "Nico",
        "Fanie",
        "Deon",
        "Gideon",
        "Koos",
        "Bennie",
        "Werner",
        "Tiaan",
        "Lourens",
        "Jaco",
        "Morné",
        "Wian",
        "Ockert",
        "Rudi",
        "Francois",
        "Anton",
        "Braam",
        "Corné",
        "Ernst",
        "Gustav",
        "Louwrens",
        "Abraham",
        "Adriaan",
        "Albertus",
        "Alwyn",
        "André",
        "Attie",
        "Barnard",
        "Bernardus",
        "Boetie",
        "Burger",
        "Carel",
        "Christo",
        "Daniël",
        "David",
        "Dawid",
        "De Wet",
        "Douw",
        "Ebenhaeser",
        "Eugene",
        "Ewald",
        "Faan",
        "Ferdinand",
        "Flip",
        "Gerrit",
        "Gert",
        "Giel",
        "Hein",
        "Heinrich",
        "Helgard",
        "Herman",
        "Hercules",
        "Ignatius",
        "Izak",
        "Jacques",
        "Jannie",
        "Jasper",
        "Johannes",
        "Jurie",
        "Kalie",
        "Karel",
        "Kerneels",
        "Klaas",
        "Leon",
        "Lodewyk",
        "Louis",
        "Ludwig",
        "Manie",
        "Marnus",
        "Matthys",
        "Michiel",
        "Neels",
        "Nicolaas",
        "Otto",
        "Paul",
        "Philip",
        "Quintus",
        "Rassie",
        "Reghard",
        "Reinhardt",
        "Roelof",
        "Ruben",
        "Sarel",
        "Servaas",
        "Sias",
        "Stefan",
        "Thys",
        "Tobias",
        "Waldo",
        "Wikus",
        "Wilhelm",
        "Zander",
        "Bartholomeus",
        "Gerhardus",
        "Johann",
        "Marthinus",
        "Willie",
        "Pietie",
        "Hendrikus",
        "Christoffel",
        "Lucas",
    )

    # Authentieke Afrikaanse vroulike voorname
    first_names_female = (
        "Anika",
        "Marié",
        "Elmarie",
        "Susanna",
        "Johanna",
        "Maria",
        "Petronella",
        "Aletta",
        "Hester",
        "Magdalena",
        "Christina",
        "Annelie",
        "Marliese",
        "Lize",
        "Marlien",
        "Chané",
        "Elmien",
        "Renske",
        "Karien",
        "Marize",
        "Ilse",
        "Riana",
        "Wilna",
        "Suné",
        "Anke",
        "Elana",
        "Mariska",
        "Nadia",
        "Lizelle",
        "Marisa",
        "Elsabé",
        "Retha",
        "Corlia",
        "Marina",
        "Cornelia",
        "Sanet",
        "Elize",
        "Yolandi",
        "Annelize",
        "Ronel",
        "Estelle",
        "Franci",
        "Karin",
        "Nerina",
        "Rina",
        "Adele",
        "Alida",
        "Amelia",
        "Anél",
        "Anelia",
        "Anet",
        "Anette",
        "Anja",
        "Annamarie",
        "Annatjie",
        "Anneke",
        "Antoinette",
        "Ansie",
        "Ariëtte",
        "Barbara",
        "Bianca",
        "Carien",
        "Carla",
        "Carmen",
        "Cecilia",
        "Charlize",
        "Chrisna",
        "Danél",
        "Delené",
        "Doret",
        "Dorothea",
        "Elandri",
        "Elbie",
        "Eleanor",
        "Elna",
        "Elsa",
        "Elsie",
        "Engela",
        "Erika",
        "Esmé",
        "Ester",
        "Frieda",
        "Gerda",
        "Hanlie",
        "Hannelie",
        "Hanri",
        "Heleen",
        "Helena",
        "Henriëtte",
        "Ilana",
        "Ina",
        "Ingrid",
        "Isabel",
        "Jana",
        "Jeanette",
        "Jolandi",
        "Juanita",
        "Katrien",
        "Kobie",
        "Laetitia",
        "Leana",
        "Lena",
        "Lettie",
        "Liana",
        "Linda",
        "Lindie",
        "Louise",
        "Madelein",
        "Magrieta",
        "Mandie",
        "Marelize",
        "Margaretha",
        "Marga",
        "Mariette",
        "Marlene",
        "Martie",
        "Melanie",
        "Michelle",
        "Monika",
        "Natasha",
        "Nellie",
        "Nicolene",
        "Nita",
        "Petro",
        "Riëtte",
    )

    # Authentieke Afrikaner vanne
    last_names = (
        "Van der Merwe",
        "Botha",
        "Pretorius",
        "Van Wyk",
        "Nel",
        "Fourie",
        "Coetzee",
        "Venter",
        "Kruger",
        "Steyn",
        "Van Zyl",
        "Du Plessis",
        "Meyer",
        "Le Roux",
        "Joubert",
        "Naudé",
        "Bezuidenhout",
        "Van Rensburg",
        "Erasmus",
        "Marais",
        "Swanepoel",
        "Vermeulen",
        "Oosthuizen",
        "Grobler",
        "Lombard",
        "Schoeman",
        "Van Niekerk",
        "Malan",
        "Terblanche",
        "Bekker",
        "Cronjé",
        "Human",
        "Labuschagne",
        "Viljoen",
        "Roux",
        "Smit",
        "Prinsloo",
        "Van Vuuren",
        "Jordaan",
        "Engelbrecht",
        "Van der Walt",
        "Rossouw",
        "Theron",
        "Wessels",
        "Badenhorst",
        "De Villiers",
        "Lategan",
        "Muller",
        "Odendaal",
        "Bester",
        "Booysen",
        "Brand",
        "Breytenbach",
        "Brink",
        "Burger",
        "Buys",
        "Claassen",
        "Coetzer",
        "Conradie",
        "De Beer",
        "De Bruin",
        "De Jager",
        "De Klerk",
        "De Kock",
        "De Lange",
        "De Wet",
        "Delport",
        "Dippenaar",
        "Dreyer",
        "Du Preez",
        "Du Toit",
        "Duvenage",
        "Ferreira",
        "Geldenhuys",
        "Gouws",
        "Greeff",
        "Greyling",
        "Hattingh",
        "Herbst",
        "Hugo",
        "Immelman",
        "Jansen",
        "Kemp",
        "Kilian",
        "Klopper",
        "Kotzé",
        "Kriel",
        "Landman",
        "Louw",
        "Lubbe",
        "Maree",
        "Mostert",
        "Nortjé",
        "Olivier",
        "Oberholzer",
        "Pienaar",
        "Potgieter",
        "Rabie",
        "Raubenheimer",
        "Rautenbach",
        "Redelinghuys",
        "Scholtz",
        "Serfontein",
        "Slabbert",
        "Snyman",
        "Stander",
        "Strauss",
        "Strydom",
        "Taljaard",
        "Van Deventer",
        "Van der Berg",
        "Van der Linde",
        "Van der Westhuizen",
        "Van Heerden",
        "Van Staden",
        "Van Tonder",
        "Van der Spuy",
        "Visagie",
        "Visser",
        "Vorster",
        "Vosloo",
        "Vlok",
        "Wolmarans",
        "Zietsman",
    )

    prefixes = ("Mnr.", "Mev.", "Mej.", "Dr.", "Prof.")
