from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{prefix}} {{first_name_male}} {{last_name}}",
    )

    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{prefix}} {{first_name_female}} {{last_name}}",
    )

    formats = formats_male + formats_female

    # Authentieke Afrikaanse manlike voorname
    first_names_male = (
        "Pieter",
        "Johan",
        "Jan",
        "Willem",
        "Hendrik",
        "Cornelius",
        "Frederik",
        "Andries",
        "Gerhard",
        "Stephanus",
        "Petrus",
        "Jacobus",
        "Christiaan",
        "Barend",
        "Dirk",
        "Kobus",
        "Danie",
        "Riaan",
        "Ruan",
        "Divan",
        "Wynand",
        "Schalk",
        "Theunis",
        "Marius",
        "Hannes",
        "Nico",
        "Fanie",
        "Deon",
        "Gideon",
        "Koos",
        "Bennie",
        "Werner",
        "Tiaan",
        "Lourens",
        "Jaco",
        "Morné",
        "Wian",
        "Ockert",
        "Rudi",
        "Francois",
        "Anton",
        "Braam",
        "Corné",
        "Ernst",
        "Gustav",
        "Louwrens",
    )

    # Authentieke Afrikaanse vroulike voorname
    first_names_female = (
        "Anika",
        "Marié",
        "Elmarie",
        "Susanna",
        "Johanna",
        "Maria",
        "Petronella",
        "Aletta",
        "Hester",
        "Magdalena",
        "Christina",
        "Annelie",
        "Marliese",
        "Lize",
        "Marlien",
        "Chané",
        "Elmien",
        "Renske",
        "Karien",
        "Marize",
        "Ilse",
        "Riana",
        "Wilna",
        "Suné",
        "Anke",
        "Elana",
        "Mariska",
        "Nadia",
        "Lizelle",
        "Marisa",
        "Elsabé",
        "Retha",
        "Corlia",
        "Marina",
        "Cornelia",
        "Sanet",
        "Elize",
        "Yolandi",
        "Annelize",
        "Ronel",
        "Estelle",
        "Franci",
        "Karin",
        "Nerina",
        "Rina",
        "Aletta",
    )

    # Authentieke Afrikaner vanne
    last_names = (
        "Van der Merwe",
        "Botha",
        "Pretorius",
        "Van Wyk",
        "Nel",
        "Fourie",
        "Coetzee",
        "Venter",
        "Kruger",
        "Steyn",
        "Van Zyl",
        "Du Plessis",
        "Meyer",
        "Le Roux",
        "Joubert",
        "Naudé",
        "Bezuidenhout",
        "Van Rensburg",
        "Erasmus",
        "Marais",
        "Swanepoel",
        "Vermeulen",
        "Oosthuizen",
        "Grobler",
        "Lombard",
        "Schoeman",
        "Van Niekerk",
        "Malan",
        "Terblanche",
        "Bekker",
        "Cronjé",
        "Human",
        "Labuschagne",
        "Viljoen",
        "Roux",
        "Smit",
        "Prinsloo",
        "Van Vuuren",
        "Jordaan",
        "Engelbrecht",
        "Van der Walt",
        "Rossouw",
        "Theron",
        "Wessels",
        "Badenhorst",
        "De Villiers",
        "Lategan",
        "Muller",
        "Odendaal",
    )

    prefixes = ("Mnr.", "Mev.", "Mej.", "Dr.", "Prof.")
