from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{prefix_female}} {{first_name_female}} {{last_name}}",
    )

    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{prefix_male}} {{first_name_male}} {{last_name}}",
    )

    formats = formats_female + formats_male

    # Authentic Urdu male given names in Perso-Arabic (Nastaliq) script.
    first_names_male = (
        "محمد",
        "احمد",
        "علی",
        "حسن",
        "حسین",
        "عمر",
        "عثمان",
        "بلال",
        "حمزہ",
        "طلحہ",
        "زبیر",
        "عبداللہ",
        "عبدالرحمن",
        "اسامہ",
        "ابوبکر",
        "عمران",
        "اسلم",
        "اکرم",
        "اشرف",
        "ارشد",
        "وقار",
        "وسیم",
        "شعیب",
        "شاہد",
        "ندیم",
        "نعمان",
        "فہد",
        "فیصل",
        "طارق",
        "ناصر",
        "سجاد",
        "اعجاز",
        "افضل",
        "اقبال",
        "انور",
        "اظہر",
        "ذوالفقار",
        "رضوان",
        "سلمان",
        "سہیل",
        "فرحان",
        "کامران",
        "مبشر",
        "مدثر",
        "منظور",
        "نبیل",
        "وحید",
        "یاسر",
        "یوسف",
        "زاہد",
        "افتخار",
        "اجمل",
    )

    # Authentic Urdu female given names in Perso-Arabic (Nastaliq) script.
    first_names_female = (
        "فاطمہ",
        "عائشہ",
        "خدیجہ",
        "مریم",
        "زینب",
        "حفصہ",
        "صفیہ",
        "آمنہ",
        "رابعہ",
        "سمیرا",
        "ثمینہ",
        "نازیہ",
        "شاہینہ",
        "فرزانہ",
        "کنول",
        "صبا",
        "ماہ نور",
        "عنبرین",
        "ناہید",
        "شمیم",
        "رخسانہ",
        "پروین",
        "نصرت",
        "بشریٰ",
        "طاہرہ",
        "رضیہ",
        "سعدیہ",
        "سلمیٰ",
        "ہما",
        "نبیلہ",
        "عظمیٰ",
        "فرحت",
        "شبانہ",
        "یاسمین",
        "ثانیہ",
        "مہوش",
        "عالیہ",
        "سائرہ",
        "رابیل",
        "حنا",
        "صنم",
        "ماریہ",
        "ارم",
        "بینش",
        "ایمن",
        "نور",
        "زارا",
        "حرا",
        "عنبر",
        "سدرہ",
    )

    first_names = first_names_male + first_names_female

    # Common Pakistani family names / castes in Perso-Arabic (Nastaliq) script.
    last_names = (
        "خان",
        "شیخ",
        "ملک",
        "بھٹی",
        "چوہدری",
        "قریشی",
        "انصاری",
        "صدیقی",
        "عباسی",
        "ہاشمی",
        "جاوید",
        "اقبال",
        "رانا",
        "گیلانی",
        "بخاری",
        "کاظمی",
        "نقوی",
        "رضوی",
        "زیدی",
        "جعفری",
        "اعوان",
        "گجر",
        "راجپوت",
        "آرائیں",
        "مغل",
        "لودھی",
        "درانی",
        "آفریدی",
        "یوسفزئی",
        "محسود",
        "وزیر",
        "بلوچ",
        "مری",
        "بگٹی",
        "سومرو",
        "لغاری",
        "کھوسہ",
        "مزاری",
        "جتوئی",
        "وٹو",
        "ٹوانہ",
        "دولتانہ",
        "سیال",
        "چیمہ",
        "ورک",
        "تارڑ",
        "بھروانہ",
        "کھر",
        "نون",
        "پراچہ",
    )

    prefixes_male = ("جناب", "محترم", "ڈاکٹر", "پروفیسر", "سید", "حاجی", "مولانا")
    prefixes_female = ("محترمہ", "ڈاکٹر", "پروفیسر", "سیدہ", "بیگم")

    prefixes = ("جناب", "محترمہ", "ڈاکٹر", "پروفیسر", "سید", "بیگم", "حاجی")
