from .. import Provider as PersonProvider


class Provider(PersonProvider):
    """
    A Faker provider for Somali (so_SO) personal names in the Latin script
    (the official Somali orthography adopted in 1972).

    Somali people traditionally carry three names: a given name, the
    father's name and the grandfather's name. There are no inherited family
    surnames, so the "last name" here is drawn from the same stock of
    personal names that function as patronymics.
    """

    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}} {{last_name}}",
        "{{first_name_male}} {{last_name}} {{last_name}}",
        "{{prefix}} {{first_name_male}} {{last_name}}",
        "{{prefix}} {{first_name_male}} {{last_name}} {{last_name}}",
    )

    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}} {{last_name}}",
        "{{first_name_female}} {{last_name}} {{last_name}}",
        "{{prefix}} {{first_name_female}} {{last_name}}",
        "{{prefix}} {{first_name_female}} {{last_name}} {{last_name}}",
    )

    formats = formats_male + formats_female

    # Authentic Somali male given names in Somali Latin orthography.
    first_names_male = (
        "Maxamed",
        "Cabdi",
        "Faarax",
        "Cali",
        "Xasan",
        "Xuseen",
        "Axmed",
        "Cumar",
        "Cusmaan",
        "Yuusuf",
        "Ibraahim",
        "Ismaaciil",
        "Maxamuud",
        "Cabdullaahi",
        "Cabdiraxmaan",
        "Cabdiqaadir",
        "Cabdinaasir",
        "Cabdifataax",
        "Cabdikariim",
        "Cabdisalaan",
        "Cabdiweli",
        "Nuur",
        "Daahir",
        "Saciid",
        "Sharmaarke",
        "Warsame",
        "Guuleed",
        "Diiriye",
        "Jaamac",
        "Barre",
        "Aweys",
        "Ducaale",
        "Gaas",
        "Rooble",
        "Samatar",
        "Siyaad",
        "Xirsi",
        "Iidow",
        "Kaahin",
        "Muuse",
        "Qaasim",
        "Yaasiin",
        "Geedi",
        "Aadan",
        "Cawaale",
        "Deeq",
        "Haaruun",
        "Fiqi",
        "Beydaan",
        "Suldaan",
        "Liibaan",
        "Farhaan",
        "Kaariye",
        "Faysal",
        "Xamse",
        "Aden",
        "Cabdisamad",
    )

    # Authentic Somali female given names in Somali Latin orthography.
    first_names_female = (
        "Hodan",
        "Xaawo",
        "Faadumo",
        "Aamino",
        "Caasho",
        "Xaliimo",
        "Sahra",
        "Ubax",
        "Deeqa",
        "Ifraax",
        "Ayaan",
        "Nasteexo",
        "Naciima",
        "Fowsiya",
        "Sagal",
        "Hibaaq",
        "Idil",
        "Muna",
        "Muniira",
        "Kaltuun",
        "Khadiija",
        "Zamzam",
        "Shukri",
        "Sucaad",
        "Ruqiya",
        "Bilan",
        "Canab",
        "Farxiya",
        "Filsan",
        "Hani",
        "Istaahil",
        "Leyla",
        "Maryan",
        "Maka",
        "Qamar",
        "Raxma",
        "Zaynab",
        "Shamis",
        "Warsan",
        "Yasmiin",
        "Amran",
        "Barni",
        "Cawo",
        "Dahabo",
        "Xabiiba",
        "Saciida",
        "Fartuun",
        "Amal",
        "Asli",
        "Baxsan",
        "Cambaro",
        "Dhuuxo",
        "Gacal",
        "Iimaan",
        "Halimo",
        "Nimco",
    )

    first_names = first_names_male + first_names_female

    # Somali patronymics ("last names") are drawn from personal names,
    # since Somalis do not use inherited family surnames.
    last_names = (
        "Cabdi",
        "Maxamed",
        "Cali",
        "Xasan",
        "Xuseen",
        "Yuusuf",
        "Axmed",
        "Faarax",
        "Cumar",
        "Cusmaan",
        "Warsame",
        "Guuleed",
        "Diiriye",
        "Jaamac",
        "Barre",
        "Nuur",
        "Aweys",
        "Ducaale",
        "Gaas",
        "Rooble",
        "Samatar",
        "Siyaad",
        "Xirsi",
        "Iidow",
        "Kaahin",
        "Muuse",
        "Qaasim",
        "Sharmaarke",
        "Yaasiin",
        "Geedi",
        "Aadan",
        "Cabdullaahi",
        "Cabdiraxmaan",
        "Ismaaciil",
        "Ibraahim",
        "Daahir",
        "Saciid",
        "Liibaan",
        "Farhaan",
        "Kaariye",
        "Cawaale",
        "Deeq",
        "Haaruun",
        "Fiqi",
        "Beydaan",
        "Maxamuud",
        "Suldaan",
        "Waaberi",
        "Cabdiqaadir",
        "Xamse",
    )

    last_names_male = last_names
    last_names_female = last_names

    prefixes = (
        "Mudane",
        "Marwo",
        "Dr.",
        "Prof.",
        "Sheekh",
        "Xaajji",
        "Xaajiyad",
        "Suldaan",
        "Injineer",
    )
