from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{prefix}} {{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}-{{last_name}}",
        "{{first_name_female}}-{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}} {{last_name}}",
    )

    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{prefix}} {{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}-{{last_name}}",
        "{{first_name_male}}-{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}} {{last_name}}",
    )

    formats = formats_male + formats_female

    # Prenon gason otantik ann Ayiti (Haitian male given names, Latin script)
    first_names_male = (
        "Jean",
        "Pierre",
        "Jacques",
        "Marc",
        "Michel",
        "Frantz",
        "Fritz",
        "Fritznel",
        "Emmanuel",
        "Wilner",
        "Wilson",
        "Jonas",
        "Ricardo",
        "Junior",
        "Kervens",
        "Woodley",
        "Jwenson",
        "Ernst",
        "Reynold",
        "Widmarc",
        "Berthony",
        "Youri",
        "Steevens",
        "Vladimir",
        "Roosevelt",
        "Gesner",
        "Anderson",
        "Jameson",
        "Josué",
        "Wesley",
        "Dieuseul",
        "Dieunel",
        "Dieudonné",
        "Herby",
        "Chesnel",
        "Yves",
        "Robert",
        "Gérard",
        "Serge",
        "Rony",
        "Ronald",
        "Peterson",
        "Watson",
        "Mackenson",
        "Evens",
        "Guerby",
        "Kenson",
        "Wisnel",
        "Louis",
        "Nixon",
    )

    # Prenon fi otantik ann Ayiti (Haitian female given names, Latin script)
    first_names_female = (
        "Marie",
        "Wideline",
        "Guerline",
        "Nadège",
        "Roselène",
        "Fabiola",
        "Darline",
        "Mirlande",
        "Lourdes",
        "Rose",
        "Marlène",
        "Ginette",
        "Islande",
        "Bettina",
        "Sabine",
        "Judeline",
        "Stephanie",
        "Manouchka",
        "Nathalie",
        "Naïka",
        "Kettelyne",
        "Wisline",
        "Farah",
        "Gaëlle",
        "Woodeline",
        "Bethania",
        "Mirline",
        "Rosemène",
        "Yolande",
        "Micheline",
        "Carline",
        "Edwine",
        "Josette",
        "Ketia",
        "Roseline",
        "Dieula",
        "Nirva",
        "Youseline",
        "Sophonie",
        "Immacula",
        "Marie-Carmelle",
        "Marie-Ange",
        "Marie-Lourdes",
        "Marie-Marthe",
        "Djennie",
        "Berthe",
        "Anoucheka",
        "Louinette",
        "Esther",
        "Chelsea",
    )

    first_names = first_names_male + first_names_female

    # Siyati otantik ann Ayiti (Haitian surnames, French-derived, Latin script)
    last_names = (
        "Pierre",
        "Jean",
        "Joseph",
        "Charles",
        "Louis",
        "Baptiste",
        "Jean-Baptiste",
        "Fils-Aimé",
        "Bien-Aimé",
        "Toussaint",
        "Désir",
        "Dorval",
        "Étienne",
        "François",
        "Cadet",
        "Célestin",
        "Duval",
        "Exantus",
        "Casimir",
        "Chéry",
        "Beauvoir",
        "Delva",
        "Augustin",
        "Bazile",
        "Belizaire",
        "Dorléans",
        "Dumas",
        "Estimé",
        "Fanfan",
        "Georges",
        "Hyppolite",
        "Innocent",
        "Jeune",
        "Lafleur",
        "Laguerre",
        "Lamour",
        "Léveillé",
        "Métellus",
        "Moïse",
        "Noël",
        "Nicolas",
        "Paul",
        "Philippe",
        "Prophète",
        "Raymond",
        "Saint-Fleur",
        "Saint-Jean",
        "Saint-Louis",
        "Sylvain",
        "Théard",
        "Vil",
        "Voltaire",
        "Zamor",
        "Antoine",
        "Fleurant",
        "Guillaume",
    )

    prefixes = ("Dr", "Me", "M.", "Mme", "Mlle")
