from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{prefix}} {{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}-{{last_name}}",
        "{{first_name_female}}-{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}} {{last_name}}",
    )

    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{prefix}} {{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}-{{last_name}}",
        "{{first_name_male}}-{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}} {{last_name}}",
    )

    formats = formats_male + formats_female

    # Prenon gason otantik ann Ayiti (Haitian male given names, Latin script)
    first_names_male = (
        "Jean",
        "Pierre",
        "Jacques",
        "Marc",
        "Michel",
        "Frantz",
        "Fritz",
        "Fritznel",
        "Emmanuel",
        "Wilner",
        "Wilson",
        "Jonas",
        "Ricardo",
        "Junior",
        "Kervens",
        "Woodley",
        "Jwenson",
        "Ernst",
        "Reynold",
        "Widmarc",
        "Berthony",
        "Youri",
        "Steevens",
        "Vladimir",
        "Roosevelt",
        "Gesner",
        "Anderson",
        "Jameson",
        "Josué",
        "Wesley",
        "Dieuseul",
        "Dieunel",
        "Dieudonné",
        "Herby",
        "Chesnel",
        "Yves",
        "Robert",
        "Gérard",
        "Serge",
        "Rony",
        "Ronald",
        "Peterson",
        "Watson",
        "Mackenson",
        "Evens",
        "Guerby",
        "Kenson",
        "Wisnel",
        "Louis",
        "Nixon",
        "Wisly",
        "Wilkens",
        "Wilguens",
        "Wilbert",
        "Willy",
        "Widley",
        "Wideson",
        "Windsor",
        "Wagner",
        "Stanley",
        "Stevenson",
        "Schneider",
        "Samuel",
        "Roland",
        "Rodrigue",
        "Rulx",
        "Renel",
        "Renaud",
        "Roody",
        "Osner",
        "Osnel",
        "Oldyn",
        "Nathan",
        "Nadson",
        "Mackendy",
        "Manno",
        "Luckner",
        "Luckson",
        "Leonard",
        "Kesner",
        "Kesler",
        "Kervin",
        "Kendy",
        "Judler",
        "Jimmy",
        "Jerry",
        "Jhonny",
        "Gary",
        "Garry",
        "Gregory",
        "Gaston",
        "Franck",
        "Frankel",
        "Franky",
        "Fresnel",
        "Fenel",
        "Fénelon",
        "Evenson",
        "Elie",
        "Édouard",
        "Edzer",
        "Ednel",
        "Duckens",
        "Dukens",
        "Destin",
        "Denis",
        "Daniel",
        "David",
        "Carlo",
        "Carlos",
        "Claudy",
        "Cliford",
        "Chrislin",
        "Bertrand",
        "Belony",
        "Bazelais",
        "Alix",
        "Alphonse",
        "André",
        "Antonio",
        "Arnold",
        "Astrel",
        "Bruno",
        "Théodore",
        "Cassius",
        "Kenley",
        "Guerlin",
        "Wildo",
    )

    # Prenon fi otantik ann Ayiti (Haitian female given names, Latin script)
    first_names_female = (
        "Marie",
        "Wideline",
        "Guerline",
        "Nadège",
        "Roselène",
        "Fabiola",
        "Darline",
        "Mirlande",
        "Lourdes",
        "Rose",
        "Marlène",
        "Ginette",
        "Islande",
        "Bettina",
        "Sabine",
        "Judeline",
        "Stephanie",
        "Manouchka",
        "Nathalie",
        "Naïka",
        "Kettelyne",
        "Wisline",
        "Farah",
        "Gaëlle",
        "Woodeline",
        "Bethania",
        "Mirline",
        "Rosemène",
        "Yolande",
        "Micheline",
        "Carline",
        "Edwine",
        "Josette",
        "Ketia",
        "Roseline",
        "Dieula",
        "Nirva",
        "Youseline",
        "Sophonie",
        "Immacula",
        "Marie-Carmelle",
        "Marie-Ange",
        "Marie-Lourdes",
        "Marie-Marthe",
        "Djennie",
        "Berthe",
        "Anoucheka",
        "Louinette",
        "Esther",
        "Chelsea",
        "Guerlande",
        "Guerdine",
        "Gladys",
        "Gina",
        "Guerlyne",
        "Hermione",
        "Ismaëlle",
        "Ivrose",
        "Jessica",
        "Jennifer",
        "Johanne",
        "Judith",
        "Junie",
        "Kesline",
        "Ketlyne",
        "Lamercie",
        "Lourdenie",
        "Loudmie",
        "Lovely",
        "Magalie",
        "Marjorie",
        "Martine",
        "Merline",
        "Mimose",
        "Mona",
        "Myriam",
        "Nadia",
        "Nadine",
        "Naomie",
        "Nephtalie",
        "Noldine",
        "Olande",
        "Paola",
        "Pascale",
        "Peggy",
        "Phara",
        "Rachelle",
        "Régine",
        "Ricarda",
        "Roberta",
        "Rochelle",
        "Rodline",
        "Rosana",
        "Rosette",
        "Rosita",
        "Ruth",
        "Sandra",
        "Samantha",
        "Sherlie",
        "Sherline",
        "Sonia",
        "Stephania",
        "Suzette",
        "Suze",
        "Tamara",
        "Tania",
        "Vanessa",
        "Venise",
        "Viergelie",
        "Wilna",
        "Wislande",
        "Wivine",
        "Yanick",
        "Yveline",
        "Zaïda",
        "Anaïse",
        "Bernadette",
        "Claudette",
        "Danielle",
        "Emmanuela",
        "Fedora",
        "Florence",
        "Gemma",
        "Herolde",
        "Ketsia",
        "Marie-Denise",
        "Marie-Yolène",
        "Nadège-Rose",
        "Vierge",
    )

    first_names = first_names_male + first_names_female

    # Siyati otantik ann Ayiti (Haitian surnames, French-derived, Latin script)
    last_names = (
        "Pierre",
        "Jean",
        "Joseph",
        "Charles",
        "Louis",
        "Baptiste",
        "Jean-Baptiste",
        "Fils-Aimé",
        "Bien-Aimé",
        "Toussaint",
        "Désir",
        "Dorval",
        "Étienne",
        "François",
        "Cadet",
        "Célestin",
        "Duval",
        "Exantus",
        "Casimir",
        "Chéry",
        "Beauvoir",
        "Delva",
        "Augustin",
        "Bazile",
        "Belizaire",
        "Dorléans",
        "Dumas",
        "Estimé",
        "Fanfan",
        "Georges",
        "Hyppolite",
        "Innocent",
        "Jeune",
        "Lafleur",
        "Laguerre",
        "Lamour",
        "Léveillé",
        "Métellus",
        "Moïse",
        "Noël",
        "Nicolas",
        "Paul",
        "Philippe",
        "Prophète",
        "Raymond",
        "Saint-Fleur",
        "Saint-Jean",
        "Saint-Louis",
        "Sylvain",
        "Théard",
        "Vil",
        "Voltaire",
        "Zamor",
        "Antoine",
        "Fleurant",
        "Guillaume",
    )

    prefixes = ("Dr", "Me", "M.", "Mme", "Mlle")
