from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{prefix_male}} {{first_name_male}} {{last_name}}",
    )

    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{prefix_female}} {{first_name_female}} {{last_name}}",
    )

    formats = formats_male + formats_female

    # Praenomina et nomina virorum Romanorum (authentic classical Latin)
    first_names_male = (
        "Marcus",
        "Gaius",
        "Lucius",
        "Publius",
        "Quintus",
        "Titus",
        "Gnaeus",
        "Aulus",
        "Decimus",
        "Servius",
        "Tiberius",
        "Manius",
        "Appius",
        "Numerius",
        "Spurius",
        "Sextus",
        "Vibius",
        "Kaeso",
        "Mamercus",
        "Postumus",
        "Aurelius",
        "Antonius",
        "Augustus",
        "Claudius",
        "Cornelius",
        "Fabius",
        "Flavius",
        "Valerius",
        "Octavius",
        "Iulius",
        "Maximus",
        "Severus",
        "Cassius",
        "Brutus",
        "Cato",
        "Cicero",
        "Fabricius",
        "Scipio",
        "Germanicus",
        "Vespasianus",
        "Hadrianus",
        "Traianus",
        "Constantinus",
        "Aemilius",
    )

    # Nomina feminarum Romanarum (authentic classical Latin)
    first_names_female = (
        "Iulia",
        "Cornelia",
        "Claudia",
        "Livia",
        "Octavia",
        "Antonia",
        "Aemilia",
        "Flavia",
        "Valeria",
        "Fabia",
        "Aurelia",
        "Domitia",
        "Agrippina",
        "Drusilla",
        "Fulvia",
        "Terentia",
        "Tullia",
        "Servilia",
        "Calpurnia",
        "Poppaea",
        "Messalina",
        "Vipsania",
        "Marcella",
        "Porcia",
        "Sabina",
        "Faustina",
        "Lucilla",
        "Plautilla",
        "Iunia",
        "Sempronia",
        "Caecilia",
        "Hortensia",
        "Metella",
        "Aquilia",
        "Pompeia",
        "Postumia",
        "Sulpicia",
        "Vibia",
        "Marcia",
        "Petronia",
        "Rubria",
        "Aelia",
        "Vitellia",
        "Lollia",
    )

    first_names = first_names_male + first_names_female

    # Nomina gentilicia (Roman gens / family names, authentic classical Latin)
    last_names = (
        "Iulius",
        "Cornelius",
        "Claudius",
        "Aurelius",
        "Flavius",
        "Valerius",
        "Aemilius",
        "Fabius",
        "Antonius",
        "Pompeius",
        "Sempronius",
        "Terentius",
        "Tullius",
        "Calpurnius",
        "Domitius",
        "Octavius",
        "Livius",
        "Marius",
        "Sulpicius",
        "Cassius",
        "Iunius",
        "Caecilius",
        "Porcius",
        "Servilius",
        "Fulvius",
        "Horatius",
        "Vergilius",
        "Ovidius",
        "Plinius",
        "Tacitus",
        "Sallustius",
        "Lucretius",
        "Manilius",
        "Papirius",
        "Quinctius",
        "Rutilius",
        "Sextius",
        "Titius",
        "Ulpius",
        "Verginius",
        "Vipsanius",
        "Aquilius",
        "Atilius",
        "Cloelius",
        "Furius",
    )

    prefixes_male = ("Dominus", "Magister", "Senator")
    prefixes_female = ("Domina", "Magistra")

    prefixes = ("Dominus", "Domina", "Magister")
