from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{prefix_female}} {{first_name_female}} {{last_name}}",
    )

    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{prefix_male}} {{first_name_male}} {{last_name}}",
    )

    formats = formats_female + formats_male

    # Authentic Sindhi male given names in the Perso-Arabic (Sindhi) script.
    first_names_male = (
        "محمد",
        "علي",
        "حسن",
        "حسين",
        "عبداللہ",
        "غلام حسين",
        "غلام محمد",
        "غلام رسول",
        "رسول بخش",
        "الله بخش",
        "خدا بخش",
        "امير بخش",
        "گل حسن",
        "گل محمد",
        "نور محمد",
        "دين محمد",
        "خير محمد",
        "ولي محمد",
        "مير محمد",
        "شاه محمد",
        "فقير محمد",
        "پير بخش",
        "سنڌو",
        "ڄام",
        "ڄاڏو",
        "ڏنو",
        "سائين ڏنو",
        "اوڀايو",
        "مٺو",
        "مورو",
        "وريام",
        "ڀورو",
        "لعل بخش",
        "سومار",
        "جمعو",
        "خميسو",
        "اڪبر",
        "اصغر",
        "سليم",
        "ندیم",
        "فياض",
        "رياض",
        "اسلم",
        "اڪرم",
        "شفيق",
        "رفيق",
        "صادق",
        "ماجد",
        "وحيد",
        "رشيد",
        "مجيد",
        "عبدالرحيم",
        "عبدالغني",
        "الهڏنو",
    )

    # Authentic Sindhi female given names in the Perso-Arabic (Sindhi) script.
    first_names_female = (
        "رشيدا",
        "فاطمه",
        "عائشه",
        "مريم",
        "زينب",
        "خديجه",
        "ماروي",
        "سسئي",
        "سهڻي",
        "نوري",
        "مومل",
        "سورٺ",
        "ليلا",
        "هير",
        "بختاور",
        "الله وسائي",
        "حوران",
        "زيبان",
        "گلان",
        "بانو",
        "رابيل",
        "صنم",
        "شبانه",
        "نازيه",
        "فرزانه",
        "پروين",
        "شمشاد",
        "گلبدن",
        "حسينه",
        "اميرزادي",
        "خيرالنساء",
        "مائي",
        "ادي",
        "سيده",
        "حور",
        "نگهت",
        "عابده",
        "ثمينه",
        "رخسانه",
        "سمينه",
        "شاهده",
        "ناهيد",
        "بيبي",
        "حاڪمزادي",
        "گلستان",
    )

    first_names = first_names_male + first_names_female

    # Common Sindhi family names, tribes and castes in the Sindhi script.
    last_names = (
        "سومرو",
        "سميجو",
        "ميمڻ",
        "ابڙو",
        "لغاري",
        "چانڊيو",
        "ملاح",
        "جتوئي",
        "مري",
        "بروهي",
        "بلوچ",
        "پنهور",
        "مهر",
        "جوکيو",
        "کوسو",
        "نظاماڻي",
        "شيخ",
        "سيال",
        "مگسي",
        "ٽالپر",
        "ڀٽو",
        "زرداري",
        "مخدوم",
        "پيرزادو",
        "سيد",
        "شاهه",
        "قريشي",
        "عباسي",
        "راڄپر",
        "اُنڙ",
        "ڪلهوڙو",
        "دائودپوٽو",
        "ڪورائي",
        "رند",
        "لاکو",
        "ٿيٻو",
        "هاليپوٽو",
        "منگي",
        "ڀرڳڙي",
        "سولنگي",
        "ماڇي",
        "وساڻ",
        "سنڌي",
        "جسڪاڻي",
        "چنا",
    )

    prefixes_male = ("سائين", "مير", "پير", "سيد", "مخدوم", "وڏيرو", "ڊاڪٽر", "حاجي", "مولانا")
    prefixes_female = ("سائڻ", "ادي", "محترمه", "بيبي", "ڊاڪٽر")

    prefixes = ("سائين", "مير", "پير", "سيد", "مخدوم", "حاجي", "محترمه", "ڊاڪٽر")
