from .. import Provider as PersonProvider


class Provider(PersonProvider):
    formats_male = (
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}}",
        "{{first_name_male}} {{last_name}} {{last_name}}",
        "{{first_name_male}} {{last_name}} {{last_name}}",
        "{{first_name_male}} {{last_name}}-{{last_name}}",
        "{{prefix}} {{first_name_male}} {{last_name}}",
    )

    formats_female = (
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}}",
        "{{first_name_female}} {{last_name}} {{last_name}}",
        "{{first_name_female}} {{last_name}} {{last_name}}",
        "{{first_name_female}} {{last_name}}-{{last_name}}",
        "{{prefix}} {{first_name_female}} {{last_name}}",
    )

    formats = formats_male + formats_female

    # Authentic Basque (Euskara) masculine given names.
    first_names_male = (
        "Ander",
        "Iker",
        "Jon",
        "Unai",
        "Aitor",
        "Gorka",
        "Xabier",
        "Julen",
        "Asier",
        "Eneko",
        "Beñat",
        "Iñaki",
        "Koldo",
        "Aimar",
        "Ekaitz",
        "Ibai",
        "Oier",
        "Peru",
        "Markel",
        "Aratz",
        "Danel",
        "Endika",
        "Garikoitz",
        "Haritz",
        "Ibon",
        "Imanol",
        "Josu",
        "Kepa",
        "Lander",
        "Manex",
        "Odei",
        "Patxi",
        "Telmo",
        "Txomin",
        "Urko",
        "Zigor",
        "Aingeru",
        "Bittor",
        "Egoitz",
        "Gaizka",
        "Iraitz",
        "Mattin",
        "Oihan",
        "Sendoa",
        "Andoni",
        "Joseba",
    )

    # Authentic Basque (Euskara) feminine given names.
    first_names_female = (
        "Maite",
        "Amaia",
        "Nerea",
        "Ainhoa",
        "Leire",
        "Nekane",
        "Miren",
        "Idoia",
        "Uxue",
        "Ane",
        "Garazi",
        "Nahia",
        "June",
        "Irati",
        "Maialen",
        "Oihana",
        "Estibaliz",
        "Edurne",
        "Arantxa",
        "Begoña",
        "Itziar",
        "Lorea",
        "Nagore",
        "Saioa",
        "Udane",
        "Alaia",
        "Enara",
        "Haizea",
        "Izaro",
        "Katalin",
        "Lide",
        "Maddi",
        "Naia",
        "Onintza",
        "Zuriñe",
        "Eider",
        "Garbiñe",
        "Intza",
        "Josune",
        "Olatz",
        "Usoa",
        "Aiala",
        "Bidane",
        "Malen",
        "Nahikari",
        "Elixabete",
    )

    first_names = first_names_male + first_names_female

    # Authentic Basque toponymic surnames.
    last_names = (
        "Etxeberria",
        "Agirre",
        "Zabala",
        "Garmendia",
        "Arrieta",
        "Bilbao",
        "Elizondo",
        "Gorostiaga",
        "Larrañaga",
        "Mendizabal",
        "Urrutia",
        "Zubizarreta",
        "Aranburu",
        "Etxebarria",
        "Goikoetxea",
        "Ibarra",
        "Izagirre",
        "Landa",
        "Mujika",
        "Olabarrieta",
        "Otxoa",
        "Sagarna",
        "Telleria",
        "Urbieta",
        "Zubiaurre",
        "Aiestaran",
        "Barandiaran",
        "Elorza",
        "Gabilondo",
        "Intxausti",
        "Legarreta",
        "Madariaga",
        "Odriozola",
        "Perurena",
        "Salaberria",
        "Uranga",
        "Zumeta",
        "Berasategi",
        "Etxaniz",
        "Gaztañaga",
        "Iturralde",
        "Lasa",
        "Oiarzabal",
        "Sarasola",
        "Urkijo",
        "Bengoetxea",
    )

    # Basque courtesy titles: Jauna (Mr.), Andrea (Ms./Mrs.).
    prefixes = ("Jn.", "And.")
